import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Header
    "juan_elizondo": "Juan Elizondo",
    "overview": "Overview",
    "market_analysis": "Market Analysis",
    "land_parcels": "Land Parcels", 
    "virtual_tour": "Virtual Tour",
    "financials": "Financials",
    "properties": "Properties",
    "calculator": "Calculator",
    
    // Hero Section
    "historic_investment": "Historic Investment Opportunity",
    "prime_shovel_ready": "Prime Shovel-Ready",
    "industrial_land": "Industrial Land",
    "mcallen_district": "McAllen Industrial District",
    "premium_properties": "Only 8 premium properties left in McAllen's premier industrial district. The Valley is America's hidden gem.",
    "market_vacancy": "Market Vacancy",
    "total_portfolio": "Total Portfolio",
    "prime_land": "Prime Industrial Land",
    "view_analysis": "View Analysis",
    "download_summary": "Download Summary",
    
    // Virtual Tour
    "virtual_property_tour": "Virtual Property Tour",
    "experience_properties": "Experience our premium industrial properties through immersive virtual tours",
    
    // Market Analysis & Insights
    "market_insights": "Market Insights and Analysis",
    "industry_expert_insights": "Industry Expert Insights",
    "stay_informed": "Stay informed with the latest market analysis and investment insights from industry leaders:",
    "fed_rate_cuts": "Fed could cut rates to at least 3%, says Bank of America's Cabana",
    "fed_rate_analysis": "36K views • 4 days ago - Expert analysis on Federal Reserve rate cuts and their impact on real estate investments.",
    "rate_impact": "How will the interest rate cut impact? | Hoy Día | Telemundo",
    "rate_impact_desc": "Analysis on how rate cuts will affect real estate investments and market opportunities.",
    "fed_environment": "Analysis of Fed Rate Environment and Its Impact on Commercial Real Estate",
    "fed_environment_desc": "Expert insights on rate changes and real estate investment strategies.",
    "powell_analysis": "Everything Fed Chief Powell did 'TOO LATE' revealed",
    "powell_analysis_desc": "1 day ago - Critical analysis of Federal Reserve decisions affecting commercial real estate markets.",
    
    // Executive Summary
    "executive_summary": "Executive Summary",
    "valley_hidden_gem": "The Valley's Hidden Gem: A $12.24M land portfolio in America's most coveted industrial district",
    "mcallen_acreage": "44.17 acres of premium shovel-ready parcels on McAllen's 10th Street in the dynamic industrial growth market. Leverage Fed rate adjustments to strategically position in this compelling market where smart investors stay and grow.",
    "strategic_investment": "Strategic Investment Opportunity in McAllen",
    "only_8_properties": "Only 8 properties available in McAllen's premier industrial district. 10th Street corridor parcels with utilities ready, industrial zoning, 585,530 buildable SF. The Valley's projected 20-year boom, combined with Fed rate cuts, creates unmatched appreciation potential. This market shows exceptional resilience to changing national conditions due to unique demand drivers and limited supply.",
    "land_portfolio_value": "Land Portfolio Value",
    "price_per_acre": "Price Per Acre",
    "valley_advantage": "The Valley Advantage - America's Hidden Gem",
    "premium_industrial_location": "Premium Industrial Location: Strategic corner on 10th Street with new road development.",
    "metro_population": "900K+ Metro Population: McAllen rivals El Paso in size with strong growth trajectory.",
    "refrigerated_boom": "Refrigerated Industry Boom: Heart of produce corridor with growing demand.",
    "fed_rate_timing": "Fed Rate Cut Timing: Perfect storm for development financing and appreciation.",
    "market_resilience": "Market Resilience: Valley growth fundamentals offer stability against changing national conditions.",
    "valley_investment": "Valley Investment Opportunity - Perfect Timing",
    "why_investors_choose": "Why investors choose the Valley: Those who've done business in McAllen stay and grow; it's America's best-kept secret. Recent comps show $281K/acre for ready sites, making our $250K-$300K pricing extremely attractive. Act now to benefit from Fed rate cuts whether you build or hold. This is a compelling investment opportunity with multiple favorable scenarios in a fundamentally sound market.",
    "land_investment_highlights": "Land Investment Highlights",
    "vacancy_rate": "3% Vacancy Rate (Q3'24): Supports stable occupancy in a consolidated market.",
    "trade_volume": "$6B+ Annual Trade Volume: Supports land demand with 44% projected growth.",
    "rent_growth": "2.5% Rent Growth: Signals strong land appreciation potential.",
    "buildable_sf": "585,530 SF: Total buildable area across 44.17 premium acres - only 8 properties remaining.",
    
    // Strategic Position
    "strategic_position": "Strategic Cross-Border Position of McAllen",
    "proven_demand": "Located in McAllen's premier industrial district with proven produce/logistics demand. The Valley demonstrates market stability backed by cross-border trade through the Pharr-Reynosa Bridge. Modeled under base and stress scenarios for lender confidence and investment clarity.",
    "dynamic_transformation": "Dynamic Valley Market Transformation",
    "mcallen_dynamics": "McAllen MSA Market Dynamics: Recent third-party reports show McAllen industrial vacancy at 3.9% (Q3'24) with LTM rent growth ~1.9%–2.5%. Average rents Q2-2025 $8.43/SF with >1.3M SF under construction (CBRE Q2-2025). The Valley demonstrates consistent growth backed by cross-border trade with proven logistics demand patterns.",
    "vacancy_trend": "Vacancy Rate Trend and Rent Growth",
    "trade_distribution": "Trade Volume Distribution",
    "produce_trade": "Over $6B in annual produce trade through Pharr-Reynosa Bridge (~$47-$50B total) creates consistent demand for specialized cold storage and distribution facilities.",
    "avocados": "Avocados: $1,970M",
    "berries": "Berries: $1,100M", 
    "peppers": "Peppers: $890M",
    "onions": "Onions: $650M",
    "others": "Others: $2,440M",
    "supply_shortage": "1.5-2.5M SF: Supply shortage - Current tenant demand vs. limited available inventory.",
    "import_growth": "+10% Import Growth: Annual cross-border trade growth (Texas A&M Research).",
    "rent_trajectory": "3% Rent Trajectory: Annual rent growth backed by market fundamentals.",
    "remaining_properties": "42 Acres: Only 8 properties remaining - McAllen's premium industrial opportunities.",
    
    // Development Opportunities
    "premium_development": "Premium Land Development Opportunity",
    "raw_land_parcels": "Raw land parcels available for development on Military Highway with agricultural fields ready for industrial conversion.",
    "military_highway_development": "Military Highway Development",
    "premium_raw_land": "Premium raw land parcels ready for industrial development with excellent highway access and custom build potential.",
    "development_ready": "Development Ready - Custom Build Available",
    "total_investment": "Total Investment",
    "total_buildable": "Total Buildable", 
    "average_price": "Average Price",
    "total_acres": "Total Acres",
    "mcc_industrial_park": "MCC Industrial Park",
    "stabilized_income": "Stabilized Income Property",
    "total_site_size": "Total Site Size",
    "building_lots": "Building Lots",
    "construction_ready": "Construction Ready",
    "average_nnn_rent": "Average NNN Rent",
    "appreciation": "Appreciation",
    "cap_rate": "Cap Rate",
    "property_features": "Property Features",
    "development_ready_lots": "Development ready lots",
    "approved_industrial_zoning": "Approved industrial zoning",
    "utilities_at_site": "Utilities at site boundaries",
    "strategic_border_location": "Strategic border location",
    "premium_highway_access": "Premium highway access",
    "investment_highlights": "Investment Highlights",
    "construction_year": "Construction Year: Immediate Development",
    "occupancy": "Occupancy: Development Ready",
    "annual_noi": "Annual NOI: Land Investment",
    "investment_summary": "Investment Summary",
    "stabilized_industrial": "Stabilized industrial park with excellent tenant mix, modern facilities, and sustainable energy features generating solid cash flow.",
    "key_advantages": "Key Advantages",
    "immediate_cash_flow": "Immediate cash flow from day one",
    "credit_tenants": "Credit tenants with long-term leases",
    "prime_military_location": "Prime Military Highway location",
    "professional_management": "Professional on-site management",
    "excellent_transportation": "Excellent transportation access",
    "financial_performance": "Financial Performance",
    "stabilized_cap_rate": "8.5% stabilized cap rate",
    "annual_operating_income": "$3.89M annual net operating income",
    "occupancy_rate": "95% occupancy with quality tenants",
    "built_in_escalations": "Built-in rent escalations",
    "value_add_potential": "Value-add potential through expansions",
    
    // Financial Projections
    "financial_projections": "MCC Industrial Park - Financial Projections & Strategy",
    "comprehensive_analysis": "Comprehensive analysis of land appreciation potential, development strategies, and exit scenarios for the 44.17-acre portfolio.",
    "land_portfolio_summary": "Land Portfolio Investment Summary",
    "total_land_investment": "Total Land Investment",
    "average_acre_price": "Average Price Per Acre",
    "annual_carrying_costs": "Annual Carrying Costs",
    "projected_appreciation": "Projected Appreciation",
    "year_value": "4-Year Value (12% avg)",
    "key_assumptions": "Key Land Investment Assumptions",
    "market_fundamentals": "Market Fundamentals",
    "land_appreciation": "Land Appreciation: 10-15% annually",
    "carrying_costs": "Carrying Costs: 2-3% annually",
    "land_pricing": "Land Pricing",
    "premium_lots": "Premium Lots: $300K/acre",
    "standard_lots": "Standard Lots: $265K/acre",
    "market_comps": "Market Comps: $281K/acre average",
    "development_potential": "Development Potential",
    "optional_dry_warehouse": "Optional Dry Warehouse: $120/SF",
    "optional_refrigerated": "Optional Refrigerated Warehouse: $200-220/SF",
    "shovel_ready_land": "Shovel-Ready Land: Immediate",
    "land_roi_profile": "Land Investment Return Profile",
    "conservative_projections": "Conservative land appreciation projections based on market fundamentals: 3% vacancy (Q3'24), $6B+ trade volume, and current rate environment.",
    "annual_land_appreciation": "10-15%: Annual Land Appreciation",
    "exit_premium": "20-30%: Exit Premium (2-3 years)",
    "annual_carrying": "2-3%: Annual Carrying Costs",
    "buyer_development_options": "Buyer Development Options (Optional)",
    "if_developed": "If developed: Dry warehouse could generate 9.7-13% ROI post-construction; refrigerated 6.5-8.8%. Costs: $120/SF dry, $200-220/SF refrigerated – but land purchase first unlocks your vision.",
    
    // Location Advantages
    "strategic_connectivity": "Strategic Location & Connectivity",
    "premium_positioning": "Premium positioning adjacent to South McAllen Industrial Park with direct access to international bridges and commercial corridors.",
    "key_distances": "Key Distances",
    "ih2_interstate": "IH-2 Interstate: 3 miles",
    "toll_road": "365 Toll Road: 1 mile",
    "anzalduas_bridge": "Anzalduas Bridge: 3 miles",
    "mcallen_bridge": "McAllen-Hidalgo Bridge: 6 miles",
    "pharr_bridge": "Pharr-Reynosa Bridge: 7 miles",
    "strategic_border": "Strategic Border Location",
    "adjacent_industrial": "Adjacent to South McAllen Industrial Park with access to three major international bridges.",
    "texas_imports": "60% of Texas fresh produce imports",
    "transportation_infrastructure": "Transportation Infrastructure",
    "military_highway": "Military Highway (FM 1016) provides seamless connectivity to major distribution networks.",
    "annual_trucks": "223K trucks annually",
    "cross_border_commerce": "Cross-Border Commerce Hub",
    "gateway": "Gateway to over $6B in annual produce trade through Pharr-Reynosa Bridge (~$47-$50B total).",
    "imports_2024": "$8B+ imports 2024",
    "utilities_infrastructure": "Utilities Infrastructure",
    "established_utilities": "Established industrial utilities with capacity for large-scale warehouse development.",
    "construction_ready_sites": "Construction-ready sites",
    "labor_market": "Labor Market Access",
    "manufacturing_employees": "Access to over 145,000 manufacturing employees in the Rio Grande Valley region.",
    "workers": "145K+ workers",
    "development_ecosystem": "Development Ecosystem",
    "established_network": "Established network of cold storage specialists and food processing facilities.",
    "proven_market": "Proven market",
    "economic_impact": "Economic Impact & Growth Drivers",
    "regional_retail": "$17.5B: Regional retail trade",
    "population_growth": "+80K: Population growth (2012-2022)",
    "grocery_ecommerce": "21.5%: Grocery e-commerce growth",
    "daily_trucks": "200+: Daily produce trucks",
    "military_corridor": "Military Highway (FM 1016) Corridor",
    "strategically_located": "Strategically located along the main industrial transportation artery connecting McAllen to Pharr-Reynosa International Bridge, providing seamless access to Mexico's produce export economy and North American distribution networks.",
    "minutes_from_bridge": "Minutes from Pharr-Reynosa International Bridge",
    
    // Demographics
    "demographics": "Area Demographics & Market Profile",
    "strategic_positioning": "Strategic positioning in a growing market with strong economic fundamentals and expanding population base.",
    "one_mile_radius": "1-Mile Radius",
    "population": "Population",
    "avg_household_income": "Avg. Household Income",
    "median_age": "Median Age",
    "avg_home_value": "Avg. Home Value",
    "three_mile_radius": "3-Mile Radius",
    "five_mile_radius": "5-Mile Radius",
    "current_market_demographics": "Current Market Demographics",
    "five_mile_profile": "The 5-mile demographic profile demonstrates a young, growing workforce with rising household incomes, creating strong demand for distribution and logistics services in the booming Valley market.",
    "median_age_demo": "33.6 Median Age: Working-age population",
    "household_income_demo": "$72K Household Income: Solid consumer base",
    "home_value_demo": "$177K Home Value: Established community",
    
    // Strategic Industrial Ecosystem
    "strategic_industrial": "Strategic Industrial Ecosystem",
    "positioned_heart": "Positioned in the heart of McAllen's industrial corridor with direct access to key trade and logistics infrastructure.",
    "premium_industrial_positioning": "Premium Industrial Positioning",
    "strategic_site_location": "The site's strategic location adjacent to South McAllen Industrial Park development positions it at the center of the region's most dynamic industrial growth area, with established infrastructure and proven demand from major logistics operators.",
    "mcallen_foreign_trade": "McAllen Foreign Trade Zone: Duty-free processing and storage (Adjacent).",
    "mcallen_produce_terminal": "McAllen Produce Terminal: Regional produce distribution hub (2.5 miles).",
    "majestic_international": "Majestic International Trade Port: Cross-border logistics facility (4.2 miles).",
    "competitive_advantages": "Competitive Advantages",
    "military_highway_frontage": "Military Highway frontage with high visibility and truck accessibility",
    "established_industrial_corridor": "Established industrial corridor with proven tenant demand",
    "proximity_bridges": "Proximity to three international bridges for diversified trade access",
    "ready_sites": "Ready sites with infrastructure that eliminate development delays and costs",
    
    // Investment Analysis
    "strategic_investment_analysis": "Strategic Investment Analysis - The Valley Advantage",
    "exceptional_value": "Why it represents exceptional value: McAllen's premier industrial district offers attractive risk-adjusted returns with strong downside protection. The Valley's market fundamentals create sustainable growth momentum that transcends typical real estate cycles.",
    "market_risks": "Market Risks",
    "key_risk_factors": "Key Risk Factors",
    "fed_environment_costs": "Fed rate environment and financing costs",
    "valley_cycle": "Valley market cycle considerations",
    "mcallen_demand": "McAllen industrial demand fluctuations",
    "mitigation_strategies": "Mitigation Strategies",
    "post_fed_adjustments": "Post-Fed adjustments, Valley market demonstrates stability, industrial demand backed by cross-border trade fundamentals.",
    "regulatory_risks": "Regulatory Risks",
    "zoning_changes": "McAllen industrial district zoning changes",
    "development_regulations": "New McAllen development regulations",
    "property_tax": "Property tax adjustments in growing market",
    "established_zoning": "Established industrial zoning in premium district, business-friendly Valley environment, secured assessments.",
    "financial_risks": "Financial Risks",
    "interest_rate_changes": "Interest rate environment changes",
    "carrying_costs_appreciation": "Carrying costs during Valley appreciation",
    "exit_liquidity": "Exit liquidity in growing market",
    "strategic_timing": "Strategic timing consideration, modeled carrying costs vs. appreciation potential, multiple exit strategies available.",
    "valley_investment_advantages": "Valley Investment Advantages",
    "mcallen_industrial_district": "McAllen Industrial District: The Valley's most coveted industrial location",
    "street_positioning": "10th Street positioning with new road development enhancing access",
    "remaining_properties_count": "Only 8 properties remaining in this premium district",
    "metro_population_support": "900K+ Valley population supporting sustained market fundamentals",
    "produce_corridor": "Heart of America's produce distribution corridor with growing demand",
    "fed_cuts_timing": "Fed rate cuts create perfect timing for investment or development financing",
    "strategic_protection": "Strategic Investment Protection",
    "strategic_land_investment": "Strategic land investment in proven growth market with minimal construction exposure",
    "multiple_exit_strategies": "Multiple exit strategies: hold for appreciation, resell at premium, or develop",
    "mcallen_resilience": "McAllen market demonstrates resilience to changing national conditions",
    "valley_growth_projection": "Valley's 20-year growth projection provides sustained investment security",
    "proven_track_record": "Proven track record: smart investors who choose the Valley achieve lasting success",
    "optimal_timing": "Optimal timing with Fed rate cuts enhancing all strategic scenarios",
    "strategic_timing_investment": "Strategic Investment Timing",
    "next_months": "Only 8 properties remaining in McAllen's premier industrial district. Smart investors who act in the coming months will benefit from Fed rate cuts and position ahead of the curve in the Valley, America's hidden gem where those who invest stay and grow.",
    
    // Investment Process
    "investment_process": "Premium Property Investment Process",
    "initial_consultation": "Initial Property Consultation: Contact a specialist to review the 8 available properties in McAllen's industrial district.",
    "site_visit": "Site Visit & Inspection: Tour McAllen properties, verify utilities, assess development potential.",
    "investment_structuring": "Investment Structuring: Structure terms to benefit from Fed rate cuts and Valley growth.",
    "property_acquisition": "Property Acquisition: Secure your position in America's most coveted industrial district.",
    "remax_commercial": "RE/MAX Commercial Team",
    "mcallen_specialist": "Your McAllen Investment Specialist",
    "specialist_description": "Over 20 years in international real estate, specializing in Valley industrial market. Expert in McAllen industrial properties with deep knowledge of the Valley's sustained growth potential and proven track record helping investors secure million-dollar opportunities before they disappear.",
    "contact_number": "(956) 522-1481",
    "contact_million_dollar": "Contact for Million-Dollar Opportunity",
    "last_8_properties": "Last 8 Properties - Act Before Fed Cuts Drive Prices Up",
    "perfect_timing": "Perfect Timing: Only 8 properties remaining in McAllen's premier industrial district. Post-Fed rate adjustments, position your investment strategically at current market prices before the Valley's continued growth drives prices higher. This is your opportunity to get ahead in America's hidden gem!",
    "mcallen_district_stats": "McAllen Industrial District",
    "premium_unique": "Premium: 8 Unique Properties Remaining",
    "portfolio_value": "Portfolio Value",
    "metro_pop": "Metro Population",
    "fed_cuts": "Fed Cuts: Strategic Timing",
    "contact_specialist": "Contact your specialist at (956) 522-1481 TODAY - These 8 premium properties won't last in the Valley's dynamic growth market!",
    
    // Market Data Sources
    "market_data_verification": "Market Data Verification",
    "third_party_metrics": "Third-party metrics for lender-ready analysis.",
    "verified_market_sources": "Verified Market Sources",
    "vacancy_rent_data": "Vacancy & Rent Data: CBRE Q2-2025 McAllen Industrial Market Report",
    "market_avg_rent": "Market average rent: $8.43/SF",
    "under_construction": "Under construction: >1.3M SF",
    "net_absorption": "Net absorption: 33,545 SF (Q2-2025)",
    "historical_vacancy": "Historical Vacancy: Matthews South Texas Report Q3-2024",
    "mcallen_vacancy": "McAllen industrial vacancy: 3.9%",
    "ltm_rent_growth": "LTM rent growth: ~1.9%–2.5%",
    "logistics_avg": "Logistics average: $9.00/SF, Flex average: $10.14/SF",
    "cross_border_trade": "Cross-Border Trade: Pharr-Reynosa Bridge / Official Reports",
    "total_annual_trade": "Total annual trade: ~$47-$50B",
    "produce_trade_amount": "Produce trade: Over $6B",
    "texas_produce_handle": "Handles 60% of Texas fresh produce",
    "construction_costs": "Construction Costs: CBRE 2024 Construction Cost Trends",
    "dry_warehouse_cost": "Dry warehouse: ~$120/SF",
    "cold_storage_premium": "Cold storage premium required",
    "texas_costs": "Texas costs slightly below US average",
    "rate_environment": "Rate Environment: NAIOP/Altus/Kearny CRE Analysis",
    "fed_cuts_started": "Fed cuts began September 2024 (-50 bps)",
    "cre_financing_effects": "Uneven CRE financing effects",
    "treasury_increase": "5-year Treasury increased post initial cuts",
    "critical_corrections": "Critical Corrections Made",
    "previous_minimum": "Previous: 1.3% 'historic low'",
    "corrected_verified": "Corrected: 3.9% (Q3'24 verified)",
    "impact_conservative": "Impact: More conservative underwriting",
    "previous_increase": "Previous: 375% increase claim",
    "corrected_ltm": "Corrected: LTM 1.9%–2.5% growth",
    "impact_realistic": "Impact: Realistic projections",
    "previous_specific": "Previous: Specific $7.05B claim",
    "corrected_over": "Corrected: Over $6B with source attribution",
    "impact_verifiable": "Impact: Verifiable market driver",
    "previous_imminent": "Previous: 'Imminent cuts' language",
    "corrected_began": "Corrected: Cuts began September 2024, mixed CRE impact",
    "impact_accurate": "Impact: Accurate timing context",
    "lender_ready_standards": "Lender-Ready Standards Met",
    "market_data_verified": "Market Data: Third-party verified vacancy, rents, and absorption.",
    "source_attribution": "Source Attribution: CBRE, Matthews, official bridge authorities.",
    "conservative_assumptions": "Conservative Assumptions: Stress-tested scenarios with rate shocks.",
    "complete_package": "Still Required for Complete Lender Package",
    "site_legal": "Site & Legal",
    "alta_survey": "ALTA survey with metes and bounds",
    "zoning_verification": "Zoning verification letters",
    "phase_esas": "Phase I ESAs and geotechnical",
    "utilities_confirmations": "Utilities capacity confirmations",
    "financial_market": "Financial & Market",
    "closed_land_comps": "Closed land sales comps (corridor)",
    "gc_budgets": "Schematic GC budgets",
    "industrial_lease_comps": "Industrial lease comps with rents",
    "debt_term_sheets": "Debt term sheets and DSCR stress tests",
    
    // Investment Opportunities
    "investment_opportunities": "Investment Opportunities",
    "choose_strategies": "Choose between two warehouse investment strategies, each optimized for different market segments and risk profiles.",
    "dry_warehouse": "Dry Warehouse",
    "refrigerated_warehouse": "Refrigerated Warehouse",
    "average_roi": "Average ROI",
    "total_sf": "Total SF",
    "available_land": "Available Land",
    "dry_warehouse_investment": "Dry Warehouse Investment",
    "high_roi_opportunity": "High ROI opportunity with lower entry costs and strong cash-on-cash returns. Fed rate cuts make financing more attractive for traditional warehouse development.",
    "construction_cost_sf": "Construction Cost per SF",
    "annual_rent_sf": "Annual Rent per SF",
    "portfolio_average_roi": "Portfolio Average ROI",
    "total_portfolio_investment": "Total Portfolio Investment",
    "individual_opportunities": "Individual Investment Opportunities",
    "lot_premium_frontage": "Lot - Premium Frontage",
    "lot_size": "Size",
    "buildable_sf": "Buildable SF",
    "projected_roi": "Projected ROI",
    "lot_standard_frontage": "Lot - Standard Frontage",
    "fed_cuts_impact": "Fed Rate Cuts Impact on Dry Warehouse Investment",
    "financing_advantages": "Financing Advantages",
    "lower_construction_rates": "Lower construction loan rates reduce carry costs",
    "better_dscr": "Better debt service coverage ratios",
    "improved_cash_returns": "Improved cash-on-cash returns through leverage",
    "refinancing_opportunities": "Refinancing opportunities for existing developments",
    "market_movement": "Market Movement Benefits",
    "increased_business": "Increased business activity from lower borrowing costs",
    "importers_expanding": "More importers expanding operations",
    "warehouse_demand": "Higher demand for flexible warehouse space",
    "optimal_timing": "Optimal timing for new development projects",
    "complete_dry_portfolio": "Complete Dry Warehouse Portfolio",
    "total_acres_dry": "Total Acres",
    "buildable_sf_dry": "Buildable SF",
    "total_investment_dry": "Total Investment",
    "annual_rental_income": "Annual Rental Income",
    
    // Property Specifications
    "property_specifications": "Property Specifications",
    "8_lots_available": "8 Premium Industrial Lots Available - Professional Underwriting Analysis",
    "premier_district": "Located in McAllen's premier industrial district with proven logistics demand. Corrected data shows 44.17 total acres, 585,530 buildable SF - significantly larger than indicated in marketing materials.",
    "professional_analysis": "Professional Individual Lot Analysis",
    "lot_01_analysis": "Lot 01 - Professional Analysis",
    "lot_coverage": "Lot Coverage",
    "land_investment": "Land Investment",
    "coverage_normal": "Within normal range",
    "per_acre": "per Acre",
    "per_buildable_sf": "per Buildable SF",
    "plan_rent_sf": "Plan Rent/SF",
    "plan_vs_market": "Plan vs. Market Rent Analysis",
    "plan_projection": "Plan Projection",
    "annual_noi": "Annual NOI",
    "upside": "upside",
    "strategic_advantages": "Strategic Advantages",
    "direct_highway": "Direct highway access from Military Hwy",
    "strategic_industrial": "Strategic industrial location enhancing visibility",
    "premium_corner": "Premium corner position with dual frontage",
    "risk_evaluation": "Risk Evaluation",
    "verify_retention": "Verify retention pond requirements and utilities capacity",
    "investment_recommendation": "Investment Recommendation",
    "positioning_strategy": "Positioning Strategy: Ideal for smaller tenant mix with flexible warehouse configurations.",
    "lot_02_analysis": "Lot 02 - Professional Analysis",
    "improved_access": "Improved access from new road development",
    "high_visibility": "High visibility traffic on main corridor",
    "premium_frontage": "Premium location with enhanced frontage",
    "monitor_construction": "Monitor road construction timeline impact",
    "strong_dry_potential": "Strong potential for dry warehouse with visibility benefits.",
    "lot_03_analysis": "Lot 03 - Professional Analysis",
    "largest_development": "Largest development lot available in district",
    "maximum_potential": "Maximum development potential for anchor tenant",
    "strategic_central": "Strategic central position with multiple access points",
    "ensure_circulation": "Ensure adequate truck circulation for large-scale operations",
    "anchor_tenant_best": "Best suited for cold storage anchor tenant or large dry warehouse.",
    "lot_04_analysis": "Lot 04 - Professional Analysis",
    "future_expansion": "Ready for future expansion with adjacent parcels",
    "optimized_utilities": "Optimized utilities for large-scale development",
    "distribution_potential": "Distribution center potential with regional access",
    "confirm_expansion": "Confirm expansion rights and utilities upgrade costs",
    "distribution_center": "Distribution center potential - ideal for multi-tenant facility.",
    "lot_05_analysis": "Lot 05 - Professional Analysis",
    "premium_development": "Premium development site with optimal configuration",
    "multiple_access": "Multiple access points for efficient operations",
    "flexible_configuration": "Flexible configuration for various tenant types",
    "verify_parking": "Verify parking requirements for multi-tenant configuration",
    "premium_multi_tenant": "Premium multi-tenant opportunity with flexible layouts.",
    "lot_06_analysis": "Lot 06 - Professional Analysis",
    "value_positioning": "Value positioning below district average",
    "rapid_development": "Ready for rapid development with minimal site work",
    "strong_roi": "Strong ROI potential with current market rents",
    "investigate_pricing": "Investigate below-market pricing factors",
    "value_play": "Value play - high ROI potential with immediate development.",
    "lot_07_analysis": "Lot 07 - Professional Analysis",
    "coverage_above": "Above typical range",
    "higher_density": "Higher density development potential in portfolio",
    "exceptional_ratio": "Exceptional SF per acre ratio",
    "compact_site": "Compact site maximizes building efficiency",
    "high_density": "High density requires careful site planning and circulation",
    "coverage_flag": "Coverage Flag: Above 65% - confirm zoning compliance",
    "specialized_warehouse": "Specialized high-density warehouse opportunity.",
    "lot_08_analysis": "Lot 08 - Professional Analysis",
    "coverage_below": "Below efficient range",
    "largest_acreage": "Largest acreage in portfolio for future expansion",
    "multiple_phases": "Possible multiple development phases",
    "strategic_land": "Strategic land investment with appreciation potential",
    "low_initial": "Low initial building density - focus on land appreciation",
    "coverage_flag_below": "Coverage Flag: Below 20% - verify site restrictions",
    "premium_land": "Premium land investment with future development potential.",
    "portfolio_summary": "8-Lot Portfolio Summary",
    "professional_underwriting": "Professional underwriting analysis - McAllen Industrial District, TX",
    "coverage_flags": "Coverage Flags",
    "data_reconciliation": "Data vs. Marketing Materials Reconciliation",
    "marketing_indicated": "Indicated in Marketing Materials:",
    "verified_site_plan": "Verified from Site Plan:",
    "critical_correction": "Critical Correction Required:",
    "significantly_more": "Portfolio contains significantly more developable area than indicated in marketing materials. Lots 7 and 8 square footages were transposed in original materials.",
    "portfolio_noi": "Portfolio NOI Potential (Annual)",
    "mixed_development": "Mixed Development Scenario (Plan Projection): Varies",
    "all_dry_warehouse": "All Dry Warehouse",
    "all_refrigerated": "All Refrigerated Warehouse",
    "portfolio_strategies": "Portfolio Investment Strategies",
    "land_hold_strategy": "Land Hold Strategy",
    "lower_capital": "Lower initial capital requirement with 8-12% annual appreciation potential.",
    "dry_development": "Dry Warehouse Development",
    "stabilized_roi": "8.5-9.0% stabilized ROI through value creation and cash flow.",
    "refrigerated_development": "Refrigerated Warehouse Development",
    "cold_storage_roi": "7.6-7.9% ROI with specialized cold storage premium.",
    "professional_investment": "Professional Investment Analysis",
    "comprehensive_analysis": "Comprehensive analysis of investment strategies, risk assessment, and due diligence documentation",
    "no_construction_risk": "No construction risk or tenant leasing risk",
    "flexibility_develop": "Flexibility to develop or sell at optimal market timing",
    "lower_capital_initial": "Lower initial capital requirement",
    "historical_performance": "Based on historical performance of premium industrial land",
    "risk_considerations": "Risk Considerations",
    "no_immediate_income": "No immediate income generation",
    "market_fluctuations": "Subject to market appreciation fluctuations",
    "carrying_costs": "Annual carrying costs reduce net returns",
    "immediate_income": "Immediate income generation upon lease-up",
    "higher_returns": "Higher returns through value creation",
    "long_term_cash": "Long-term cash flow from quality industrial assets",
    "value_added": "Value-added through operational improvements",
    "construction_cost_risk": "Construction cost inflation risk",
    "tenant_leasing": "Tenant leasing timeline uncertainty",
    "market_rent": "Market rent volatility during development",
    "premium_rents": "Premium rents for specialized cold storage",
    "strong_tenant": "Strong tenant demand from produce industry",
    "high_barriers": "High barriers to entry",
    "long_term_relationships": "Long-term tenant relationships",
    "higher_complexity": "Higher complexity and construction costs",
    "specialized_equipment": "Specialized equipment maintenance requirements",
    "limited_tenant": "Limited tenant pool for cold storage",
    
    // Chat
    "chat_with_juan": "Chat with Juan",
    
    // Navigation
    "home": "Home",
    "analysis": "Analysis",
    "chat": "Chat", 
    "menu": "Menu",
    
    // Common
    "acres": "Acres",
    "close": "Close",
    "million": "Million",
    "sf": "SF",
    "view_details": "View Details",
    "contact_now": "Contact Now",
    "learn_more": "Learn More"
  },
  es: {
    // Header
    "juan_elizondo": "Juan Elizondo",
    "overview": "Resumen",
    "market_analysis": "Análisis de Mercado",
    "land_parcels": "Parcelas de Terreno",
    "virtual_tour": "Tour Virtual",
    "financials": "Financieras",
    "properties": "Propiedades",
    "calculator": "Calculadora",
    
    // Hero Section
    "historic_investment": "Oportunidad de Inversión Histórica",
    "prime_shovel_ready": "Terreno Industrial Premium",
    "industrial_land": "Listo para Construir",
    "mcallen_district": "Distrito Industrial de McAllen",
    "premium_properties": "Solo quedan 8 propiedades premium en el distrito industrial premier de McAllen. El Valle es la joya escondida de América.",
    "market_vacancy": "Vacancia de Mercado",
    "total_portfolio": "Portafolio Total",
    "prime_land": "Terreno Industrial Premium",
    "view_analysis": "Ver Análisis",
    "download_summary": "Descargar Resumen",
    
    // Virtual Tour
    "virtual_property_tour": "Tour Virtual de Propiedades",
    "experience_properties": "Experimenta nuestras propiedades industriales premium a través de recorridos virtuales inmersivos",
    
    // Market Analysis & Insights
    "market_insights": "Perspectivas y Análisis del Mercado",
    "industry_expert_insights": "Perspectivas de Expertos de la Industria",
    "stay_informed": "Mantente informado con el análisis de mercado más reciente y perspectivas de inversión de líderes de la industria:",
    "fed_rate_cuts": "El Fed podría reducir tasas a al menos 3%, dice Cabana de Bank of America",
    "fed_rate_analysis": "36K vistas • Hace 4 días - Análisis experto sobre recortes de tasas del Federal Reserve y su impacto en inversiones inmobiliarias.",
    "rate_impact": "¿Cómo impactará la baja de tasas de interés? | Hoy Día | Telemundo",
    "rate_impact_desc": "Análisis sobre cómo los recortes de tasas afectarán las inversiones inmobiliarias y oportunidades de mercado.",
    "fed_environment": "Análisis del Entorno de Tasas del Fed y su Impacto en Bienes Raíces Comerciales",
    "fed_environment_desc": "Perspectivas de expertos sobre cambios de tasas y estrategias de inversión inmobiliaria.",
    "powell_analysis": "Todo lo que el presidente del Fed, Powell, hizo 'DEMASIADO TARDE' revelado",
    "powell_analysis_desc": "Hace 1 día - Análisis crítico de decisiones del Federal Reserve que afectan los mercados inmobiliarios comerciales.",
    
    // Executive Summary
    "executive_summary": "Resumen Ejecutivo",
    "valley_hidden_gem": "La Joya Oculta del Valle: Un portafolio de terrenos de $12.24M en el distrito industrial más codiciado de América",
    "mcallen_acreage": "44.17 acres de parcelas premium listas para construir en la calle 10 de McAllen, en el dinámico mercado de crecimiento industrial. Aprovecha los ajustes de tasas del Fed para posicionarte estratégicamente en este atractivo mercado donde los inversionistas inteligentes permanecen y crecen.",
    "strategic_investment": "Oportunidad de Inversión Estratégica en McAllen",
    "only_8_properties": "Solo 8 propiedades disponibles en el principal distrito industrial de McAllen. Parcelas en el corredor de la calle 10 con servicios listos, zonificación industrial, 585,530 SF construibles. El auge proyectado de 20 años del Valle, combinado con recortes de tasas del Fed, crea un potencial de apreciación inigualable. Este mercado muestra una resiliencia excepcional frente a condiciones nacionales cambiantes debido a sus únicos impulsores de demanda y oferta limitada.",
    "land_portfolio_value": "Valor del Portafolio de Terrenos",
    "price_per_acre": "Precio por Acre",
    "valley_advantage": "La Ventaja del Valle - La Joya Oculta de América",
    "premium_industrial_location": "Ubicación Industrial Premium: Esquina estratégica en la calle 10 con nuevo desarrollo vial.",
    "metro_population": "Población Metropolitana de 900K+: McAllen rivaliza con El Paso en tamaño con una fuerte trayectoria de crecimiento.",
    "refrigerated_boom": "Auge de la Industria Refrigerada: Corazón del corredor de productos agrícolas con demanda creciente.",
    "fed_rate_timing": "Momento de Recortes de Tasas del Fed: Tormenta perfecta para financiamiento de desarrollo y apreciación.",
    "market_resilience": "Resiliencia del Mercado: Fundamentos de crecimiento del Valle ofrecen estabilidad frente a condiciones nacionales cambiantes.",
    "valley_investment": "Oportunidad de Inversión en el Valle - Momento Perfecto",
    "why_investors_choose": "Por qué los inversionistas eligen el Valle: Quienes han hecho negocios en McAllen se quedan y crecen; es el secreto mejor guardado de América. Comparables recientes muestran $281K/acre para sitios listos, haciendo que nuestro precio de $250K-$300K sea extremadamente atractivo. Actúa ahora para beneficiarte de los recortes de tasas del Fed, ya sea que construyas o mantengas. Esta es una oportunidad de inversión convincente con múltiples escenarios favorables en un mercado fundamentalmente sólido.",
    "land_investment_highlights": "Aspectos Destacados de la Inversión en Terrenos",
    "vacancy_rate": "3% Tasa de Desocupación (3T24): Apoya la ocupación estable en un mercado consolidado.",
    "trade_volume": "$6B+ Volumen de Comercio Anual: Soporta la demanda de terrenos con un crecimiento proyectado del 44%.",
    "rent_growth": "2.5% Crecimiento de Rentas: Señala un fuerte potencial de apreciación de terrenos.",
    "buildable_sf": "585,530 SF: Área total construible en 44.17 acres premium - solo 8 propiedades restantes.",
    
    // Strategic Position
    "strategic_position": "Posición Transfronteriza Estratégica de McAllen",
    "proven_demand": "Ubicado en el principal distrito industrial de McAllen con demanda probada de productos agrícolas/logística. El Valle demuestra estabilidad de mercado respaldada por el comercio transfronterizo a través del Puente Pharr-Reynosa. Modelado bajo escenarios base y de estrés para confianza de prestamistas y claridad de inversión.",
    "dynamic_transformation": "Transformación Dinámica del Mercado del Valle",
    "mcallen_dynamics": "Dinámicas del Mercado MSA de McAllen: Informes recientes de terceros muestran una desocupación industrial en McAllen del 3.9% (3T24) con un crecimiento de rentas LTM ~1.9%–2.5%. Rentas promedio en 2T-2025 de $8.43/SF con >1.3M SF en construcción (CBRE 2T-2025). El Valle demuestra un crecimiento consistente respaldado por el comercio transfronterizo con patrones de demanda logística probados.",
    "vacancy_trend": "Tendencia de Tasa de Desocupación y Crecimiento de Rentas",
    "trade_distribution": "Distribución de Volumen de Comercio",
    "produce_trade": "Más de $6B en comercio anual de productos agrícolas a través del Puente Pharr-Reynosa (~$47-$50B total) crea una demanda constante para instalaciones especializadas de almacenamiento en frío y distribución.",
    "avocados": "Aguacates: $1,970M",
    "berries": "Bayas: $1,100M",
    "peppers": "Pimientos: $890M",
    "onions": "Cebollas: $650M",
    "others": "Otros: $2,440M",
    "supply_shortage": "1.5-2.5M SF: Escasez de oferta - Demanda actual de inquilinos vs. inventario limitado disponible.",
    "import_growth": "+10% Crecimiento de Importaciones: Crecimiento anual del comercio transfronterizo (Investigación de Texas A&M).",
    "rent_trajectory": "3% Trayectoria de Rentas: Crecimiento anual de rentas respaldado por fundamentos del mercado.",
    "remaining_properties": "42 Acres: Solo 8 propiedades restantes - Oportunidades industriales premium de McAllen.",
    
    // Development Opportunities
    "premium_development": "Oportunidad de Desarrollo de Terrenos Premium",
    "raw_land_parcels": "Parcelas de terreno crudo disponibles para desarrollo en Military Highway con campos agrícolas listos para conversión industrial.",
    "military_highway_development": "Desarrollo en Military Highway",
    "premium_raw_land": "Parcelas de terreno crudo premium listas para desarrollo industrial con excelente acceso a la autopista y potencial de construcción a medida.",
    "development_ready": "Listo para Desarrollo - Construcción a Medida Disponible",
    "total_investment": "Inversión Total",
    "total_buildable": "Total Construible",
    "average_price": "Precio Promedio",
    "total_acres": "Total de Acres",
    "mcc_industrial_park": "Parque Industrial MCC",
    "stabilized_income": "Propiedad de Ingresos Estabilizados",
    "total_site_size": "Tamaño Total del Sitio",
    "building_lots": "Lotes de Edificios",
    "construction_ready": "Listo para Construcción",
    "average_nnn_rent": "Renta Promedio NNN",
    "appreciation": "Apreciación",
    "cap_rate": "Tasa de Capitalización",
    "property_features": "Características de la Propiedad",
    "development_ready_lots": "Lotes listos para desarrollo",
    "approved_industrial_zoning": "Zonificación industrial aprobada",
    "utilities_at_site": "Servicios en los límites del sitio",
    "strategic_border_location": "Ubicación estratégica en la frontera",
    "premium_highway_access": "Acceso premium a la autopista",
    "investment_highlights": "Aspectos Destacados de la Inversión",
    "construction_year": "Año de Construcción: Desarrollo Inmediato",
    "occupancy": "Ocupación: Listo para Desarrollo",
    "annual_noi": "NOI Anual: Inversión en Terrenos",
    "investment_summary": "Resumen de la Inversión",
    "stabilized_industrial": "Parque industrial estabilizado con excelente mezcla de inquilinos, instalaciones modernas y características de energía sostenible que generan un flujo de caja sólido.",
    "key_advantages": "Ventajas Clave",
    "immediate_cash_flow": "Flujo de caja inmediato desde el primer día",
    "credit_tenants": "Inquilinos de crédito con arrendamientos a largo plazo",
    "prime_military_location": "Ubicación privilegiada en Military Highway",
    "professional_management": "Gestión profesional en el sitio",
    "excellent_transportation": "Excelente acceso al transporte",
    "financial_performance": "Desempeño Financiero",
    "stabilized_cap_rate": "Tasa de capitalización estabilizada del 8.5%",
    "annual_operating_income": "$3.89M de ingreso neto operativo anual",
    "occupancy_rate": "95% de ocupación con inquilinos de calidad",
    "built_in_escalations": "Escalaciones de renta incorporadas",
    "value_add_potential": "Potencial de valor agregado mediante expansiones",
    
    // Financial Projections
    "financial_projections": "Parque Industrial MCC - Proyecciones Financieras y Estrategia",
    "comprehensive_analysis": "Análisis exhaustivo del potencial de apreciación de terrenos, estrategias de desarrollo y escenarios de salida para el portafolio de 44.17 acres.",
    "land_portfolio_summary": "Resumen de Inversión del Portafolio de Terrenos",
    "total_land_investment": "Inversión Total en Terrenos",
    "average_acre_price": "Precio Promedio por Acre",
    "annual_carrying_costs": "Costos Anuales de Mantenimiento",
    "projected_appreciation": "Apreciación Proyectada",
    "year_value": "Valor a 4 Años (12% promedio)",
    "key_assumptions": "Suposiciones Clave de la Inversión en Terrenos",
    "market_fundamentals": "Fundamentos del Mercado",
    "land_appreciation": "Apreciación de Terrenos: 10-15% anual",
    "carrying_costs": "Costos de Mantenimiento: 2-3% anual",
    "land_pricing": "Precios de Terrenos",
    "premium_lots": "Lotes Premium: $300K/acre",
    "standard_lots": "Lotes Estándar: $265K/acre",
    "market_comps": "Comparables de Mercado: $281K/acre promedio",
    "development_potential": "Potencial de Desarrollo",
    "optional_dry_warehouse": "Almacén Seco Opcional: $120/SF",
    "optional_refrigerated": "Almacén Refrigerado Opcional: $200-220/SF",
    "shovel_ready_land": "Terreno Listo para Construcción: Inmediato",
    "land_roi_profile": "Perfil de Retorno de la Inversión en Terrenos",
    "conservative_projections": "Proyecciones conservadoras de apreciación de terrenos basadas en fundamentos del mercado: 3% de desocupación (3T24), volumen de comercio de $6B+ y entorno actual de tasas.",
    "annual_land_appreciation": "10-15%: Apreciación Anual de Terrenos",
    "exit_premium": "20-30%: Prima de Salida (2-3 años)",
    "annual_carrying": "2-3%: Costos Anuales de Mantenimiento",
    "buyer_development_options": "Opciones de Desarrollo para Compradores (Opcional)",
    "if_developed": "Si se desarrolla: Almacén seco podría generar un ROI de 9.7-13% tras la construcción; refrigerado 6.5-8.8%. Costos: $120/SF seco, $200-220/SF refrigerado – pero la compra de terreno primero desbloquea tu visión.",
    
    // Location Advantages
    "strategic_connectivity": "Ubicación Estratégica y Conectividad",
    "premium_positioning": "Posicionamiento premium junto al Parque Industrial del Sur de McAllen con acceso directo a puentes internacionales y corredores comerciales.",
    "key_distances": "Distancias Clave",
    "ih2_interstate": "IH-2 Interestatal: 3 millas",
    "toll_road": "365 Toll Road: 1 milla",
    "anzalduas_bridge": "Puente Anzalduas: 3 millas",
    "mcallen_bridge": "Puente McAllen-Hidalgo: 6 millas",
    "pharr_bridge": "Puente Pharr-Reynosa: 7 millas",
    "strategic_border": "Ubicación Estratégica en la Frontera",
    "adjacent_industrial": "Adyacente al Parque Industrial del Sur de McAllen con acceso a tres puentes internacionales principales.",
    "texas_imports": "60% de las importaciones de productos frescos de Texas",
    "transportation_infrastructure": "Infraestructura de Transporte",
    "military_highway": "Military Highway (FM 1016) proporciona conectividad fluida a redes de distribución principales.",
    "annual_trucks": "223K camiones anuales",
    "cross_border_commerce": "Centro de Comercio Transfronterizo",
    "gateway": "Puerta de entrada a más de $6B en comercio anual de productos agrícolas a través del Puente Pharr-Reynosa (~$47-$50B total).",
    "imports_2024": "$8B+ importaciones 2024",
    "utilities_infrastructure": "Infraestructura de Servicios",
    "established_utilities": "Servicios industriales establecidos con capacidad para desarrollo de almacenes a gran escala.",
    "construction_ready_sites": "Sitios listos para construcción",
    "labor_market": "Acceso al Mercado Laboral",
    "manufacturing_employees": "Acceso a más de 145,000 empleados manufactureros en la región del Valle del Río Grande.",
    "workers": "145K+ trabajadores",
    "development_ecosystem": "Ecosistema de Desarrollo",
    "established_network": "Red establecida de especialistas en almacenamiento en frío y instalaciones de procesamiento de alimentos.",
    "proven_market": "Mercado probado",
    "economic_impact": "Impacto Económico y Factores de Crecimiento",
    "regional_retail": "$17.5B: Comercio minorista regional",
    "population_growth": "+80K: Crecimiento poblacional (2012-2022)",
    "grocery_ecommerce": "21.5%: Crecimiento del comercio electrónico de comestibles",
    "daily_trucks": "200+: Camiones de productos diarios",
    "military_corridor": "Corredor Military Highway (FM 1016)",
    "strategically_located": "Ubicado estratégicamente a lo largo de la arteria principal de transporte industrial que conecta McAllen con el Puente Internacional Pharr-Reynosa, proporcionando acceso fluido a la economía de exportación de productos de México y redes de distribución de América del Norte.",
    "minutes_from_bridge": "A minutos del Puente Internacional Pharr-Reynosa",
    
    // Demographics
    "demographics": "Demografía del Área y Perfil del Mercado",
    "strategic_positioning": "Posicionamiento estratégico en un mercado en crecimiento con fundamentos económicos sólidos y una base poblacional en expansión.",
    "one_mile_radius": "Radio de 1 Milla",
    "population": "Población",
    "avg_household_income": "Ingreso Promedio por Hogar",
    "median_age": "Edad Promedio",
    "avg_home_value": "Valor Promedio de Casa",
    "three_mile_radius": "Radio de 3 Millas",
    "five_mile_radius": "Radio de 5 Millas",
    "current_market_demographics": "Demografía Actual del Mercado",
    "five_mile_profile": "El perfil demográfico de 5 millas demuestra una fuerza laboral joven y en crecimiento con ingresos familiares en aumento, creando una fuerte demanda de servicios de distribución y logística en el mercado en auge del Valle.",
    "median_age_demo": "33.6 Edad Promedio: Población en edad laboral",
    "household_income_demo": "$72K Ingreso por Hogar: Base de consumidores sólida",
    "home_value_demo": "$177K Valor de Casa: Comunidad establecida",
    
    // Strategic Industrial Ecosystem
    "strategic_industrial": "Ecosistema Industrial Estratégico",
    "positioned_heart": "Ubicado en el corazón del corredor industrial de McAllen con acceso directo a infraestructura clave de comercio y logística.",
    "premium_industrial_positioning": "Posicionamiento Industrial Premium",
    "strategic_site_location": "La ubicación estratégica del sitio junto al desarrollo del Parque Industrial del Sur de McAllen lo posiciona en el centro del área de crecimiento industrial más dinámica de la región, con infraestructura establecida y demanda probada de operadores logísticos importantes.",
    "mcallen_foreign_trade": "Zona de Comercio Exterior de McAllen: Procesamiento y almacenamiento libre de impuestos (Adyacente).",
    "mcallen_produce_terminal": "Terminal de Productos de McAllen: Centro de distribución de productos agrícolas regional (2.5 millas).",
    "majestic_international": "Puerto de Comercio Internacional Majestic: Instalación logística transfronteriza (4.2 millas).",
    "competitive_advantages": "Ventajas Competitivas",
    "military_highway_frontage": "Frente a Military Highway con alta visibilidad y accesibilidad para camiones",
    "established_industrial_corridor": "Corredor industrial establecido con demanda probada de inquilinos",
    "proximity_bridges": "Proximidad a tres puentes internacionales para acceso diversificado al comercio",
    "ready_sites": "Sitios listos con infraestructura que eliminan retrasos y costos de desarrollo",
    
    // Investment Analysis
    "strategic_investment_analysis": "Análisis de Inversión Estratégica - La Ventaja del Valle",
    "exceptional_value": "Por qué representa un valor excepcional: El principal distrito industrial de McAllen ofrece retornos ajustados al riesgo atractivos con una fuerte protección contra pérdidas. Los fundamentos del mercado del Valle crean un impulso de crecimiento sostenible que trasciende los ciclos inmobiliarios típicos.",
    "market_risks": "Riesgos del Mercado",
    "key_risk_factors": "Factores de Riesgo Clave",
    "fed_environment_costs": "Entorno de tasas del Fed y costos de financiamiento",
    "valley_cycle": "Consideraciones del ciclo del mercado del Valle",
    "mcallen_demand": "Fluctuaciones de la demanda industrial en McAllen",
    "mitigation_strategies": "Estrategias de Mitigación",
    "post_fed_adjustments": "Tras los ajustes de tasas del Fed, el mercado del Valle demuestra estabilidad, la demanda industrial está respaldada por fundamentos de comercio transfronterizo.",
    "regulatory_risks": "Riesgos Regulatorios",
    "zoning_changes": "Cambios de zonificación en el distrito industrial de McAllen",
    "development_regulations": "Nuevas regulaciones de desarrollo en McAllen",
    "property_tax": "Ajustes de impuestos a la propiedad en un mercado en crecimiento",
    "established_zoning": "Zonificación industrial establecida en un distrito premium, entorno favorable para negocios en el Valle, evaluaciones aseguradas.",
    "financial_risks": "Riesgos Financieros",
    "interest_rate_changes": "Cambios en el entorno de tasas de interés",
    "carrying_costs_appreciation": "Costos de mantenimiento durante la apreciación en el Valle",
    "exit_liquidity": "Liquidez de salida en un mercado en crecimiento",
    "strategic_timing": "Consideración estratégica del momento, costos de mantenimiento modelados frente al potencial de apreciación, múltiples estrategias de salida disponibles.",
    "valley_investment_advantages": "Ventajas de Inversión en el Valle",
    "mcallen_industrial_district": "Distrito Industrial de McAllen: La ubicación industrial más codiciada del Valle",
    "street_positioning": "Posicionamiento en la calle 10 con nuevo desarrollo vial que mejora el acceso",
    "remaining_properties_count": "Solo 8 propiedades restantes en este distrito premium",
    "metro_population_support": "Población de 900K+ en el Valle que respalda fundamentos de mercado sostenidos",
    "produce_corridor": "Corazón del corredor de distribución de productos agrícolas de América con demanda creciente",
    "fed_cuts_timing": "Los recortes de tasas del Fed crean un momento perfecto para inversión o financiamiento de desarrollo",
    "strategic_protection": "Protección Estratégica de la Inversión",
    "strategic_land_investment": "Inversión en terrenos estratégicos en un mercado de crecimiento probado con exposición mínima a la construcción",
    "multiple_exit_strategies": "Múltiples estrategias de salida: mantener para apreciación, revender con prima o desarrollar",
    "mcallen_resilience": "El mercado de McAllen demuestra resiliencia frente a condiciones nacionales cambiantes",
    "valley_growth_projection": "Proyección de crecimiento de 20 años del Valle proporciona seguridad de inversión sostenida",
    "proven_track_record": "Historial probado: los inversionistas inteligentes que eligen el Valle logran un éxito duradero",
    "optimal_timing": "Momento óptimo con recortes de tasas del Fed que mejoran todos los escenarios estratégicos",
    "strategic_timing_investment": "Momento Estratégico de Inversión",
    "next_months": "Solo 8 propiedades restantes en el principal distrito industrial de McAllen. Los inversionistas inteligentes que actúen en los próximos meses se beneficiarán de los recortes de tasas del Fed y se posicionarán por delante de la curva en el Valle, la joya oculta de América donde quienes invierten se quedan y crecen.",
    
    // Investment Process
    "investment_process": "Proceso de Inversión en Propiedades Premium",
    "initial_consultation": "Consulta Inicial de Propiedades: Contacta a un especialista para revisar las 8 propiedades disponibles en el distrito industrial de McAllen.",
    "site_visit": "Visita e Inspección del Sitio: Recorre las propiedades de McAllen, verifica los servicios, evalúa el potencial de desarrollo.",
    "investment_structuring": "Estructuración de la Inversión: Estructura términos para beneficiarte de los recortes de tasas del Fed y el crecimiento del Valle.",
    "property_acquisition": "Adquisición de la Propiedad: Asegura tu posición en el distrito industrial más codiciado de América.",
    "remax_commercial": "Equipo Comercial RE/MAX",
    "mcallen_specialist": "Tu Especialista en Inversiones en McAllen",
    "specialist_description": "Más de 20 años de experiencia en bienes raíces internacionales, especializándose en el mercado industrial del Valle. Experto en propiedades industriales de McAllen con un conocimiento profundo del potencial de crecimiento sostenido del Valle y un historial probado ayudando a inversionistas a asegurar oportunidades de millones de dólares antes de que desaparezcan.",
    "contact_number": "(956) 522-1481",
    "contact_million_dollar": "Contacta para una Oportunidad de Millones de Dólares",
    "last_8_properties": "Últimas 8 Propiedades - Actúa Antes de que los Recortes del Fed Suban los Precios",
    "perfect_timing": "Momento Perfecto: Solo 8 propiedades restantes en el principal distrito industrial de McAllen. Tras los ajustes de tasas del Fed, posiciona tu inversión estratégicamente a precios de mercado actuales antes de que el crecimiento continuo del Valle eleve los precios. ¡Esta es tu oportunidad de adelantarte en la joya oculta de América!",
    "mcallen_district_stats": "Distrito Industrial de McAllen",
    "premium_unique": "Premium: 8 Propiedades Únicas Restantes",
    "portfolio_value": "Valor del Portafolio",
    "metro_pop": "Población Metropolitana",
    "fed_cuts": "Recortes del Fed: Momento Estratégico",
    "contact_specialist": "Contacta a tu especialista al (956) 522-1481 HOY - ¡Estas 8 propiedades premium no durarán en el dinámico mercado de crecimiento del Valle!",
    
    // Market Data Sources
    "market_data_verification": "Verificación de Datos de Mercado",
    "third_party_metrics": "Métricas de terceros para análisis listo para prestamistas.",
    "verified_market_sources": "Fuentes de Mercado Verificadas",
    "vacancy_rent_data": "Datos de Desocupación y Rentas: CBRE 2T-2025 Informe del Mercado Industrial de McAllen",
    "market_avg_rent": "Renta promedio de mercado: $8.43/SF",
    "under_construction": "En construcción: >1.3M SF",
    "net_absorption": "Absorción neta: 33,545 SF (2T-2025)",
    "historical_vacancy": "Desocupación Histórica: Informe del Sur de Texas de Matthews 3T-2024",
    "mcallen_vacancy": "Desocupación industrial en McAllen: 3.9%",
    "ltm_rent_growth": "Crecimiento de rentas LTM: ~1.9%–2.5%",
    "logistics_avg": "Promedio logístico: $9.00/SF, Flex promedio: $10.14/SF",
    "cross_border_trade": "Comercio Transfronterizo: Puente Pharr-Reynosa / Informes Oficiales",
    "total_annual_trade": "Comercio anual total: ~$47-$50B",
    "produce_trade_amount": "Comercio de productos agrícolas: Más de $6B",
    "texas_produce_handle": "Maneja el 60% de los productos frescos de Texas",
    "construction_costs": "Costos de Construcción: Tendencias de Costos de Construcción CBRE 2024",
    "dry_warehouse_cost": "Almacén seco: ~$120/SF",
    "cold_storage_premium": "Se requiere prima para almacenamiento en frío",
    "texas_costs": "Costos de Texas ligeramente por debajo del promedio de EE. UU.",
    "rate_environment": "Entorno de Tasas: Análisis CRE de NAIOP/Altus/Kearny",
    "fed_cuts_started": "Recortes del Fed comenzaron en septiembre de 2024 (-50 bps)",
    "cre_financing_effects": "Efectos de financiamiento CRE desiguales",
    "treasury_increase": "Tesoro a 5 años aumentó tras recortes iniciales",
    "critical_corrections": "Correcciones Críticas Realizadas",
    "previous_minimum": "Anterior: 1.3% 'mínimo histórico'",
    "corrected_verified": "Corregido: 3.9% (3T24 verificado)",
    "impact_conservative": "Impacto: Suscripción más conservadora",
    "previous_increase": "Anterior: Afirmación de aumento del 375%",
    "corrected_ltm": "Corregido: Crecimiento LTM 1.9%–2.5%",
    "impact_realistic": "Impacto: Proyecciones realistas",
    "previous_specific": "Anterior: Afirmación específica de $7.05B",
    "corrected_over": "Corregido: Más de $6B con atribución de fuente",
    "impact_verifiable": "Impacto: Impulsor de mercado verificable",
    "previous_imminent": "Anterior: Lenguaje de 'cortes inminentes'",
    "corrected_began": "Corregido: Cortes comenzaron en septiembre de 2024, impacto mixto en CRE",
    "impact_accurate": "Impacto: Contexto de tiempo preciso",
    "lender_ready_standards": "Estándares Listos para Prestamistas Cumplidos",
    "market_data_verified": "Datos de Mercado: Desocupación, rentas y absorción verificadas por terceros.",
    "source_attribution": "Atribución de Fuentes: CBRE, Matthews, autoridades oficiales del puente.",
    "conservative_assumptions": "Suposiciones Conservadoras: Escenarios probados bajo estrés con choques de tasas.",
    "complete_package": "Aún Requerido para Paquete Completo de Prestamistas",
    "site_legal": "Sitio y Legal",
    "alta_survey": "Encuesta ALTA con metes y bounds",
    "zoning_verification": "Cartas de verificación de zonificación",
    "phase_esas": "Fase I ESAs y geotecnia",
    "utilities_confirmations": "Confirmaciones de capacidad de servicios",
    "financial_market": "Financiero y de Mercado",
    "closed_land_comps": "Comps de ventas de terrenos cerradas (corredor)",
    "gc_budgets": "Presupuestos esquemáticos de GC",
    "industrial_lease_comps": "Comps de arrendamientos industriales con rentas",
    "debt_term_sheets": "Hojas de términos de deuda y pruebas de estrés DSCR",
    
    // Investment Opportunities
    "investment_opportunities": "Oportunidades de Inversión",
    "choose_strategies": "Elige entre dos estrategias de inversión en almacenes, cada una optimizada para diferentes segmentos de mercado y perfiles de riesgo.",
    "dry_warehouse": "Almacén Seco",
    "refrigerated_warehouse": "Almacén Refrigerado",
    "average_roi": "ROI Promedio",
    "total_sf": "SF Total",
    "available_land": "Terreno Disponible",
    "dry_warehouse_investment": "Inversión en Almacén Seco",
    "high_roi_opportunity": "Oportunidad de alto ROI con menores costos de entrada y fuertes retornos de efectivo sobre efectivo. Los recortes de tasas del Fed hacen que el financiamiento sea más atractivo para el desarrollo de almacenes tradicionales.",
    "construction_cost_sf": "Costo de Construcción por SF",
    "annual_rent_sf": "Renta Anual por SF",
    "portfolio_average_roi": "ROI Promedio del Portafolio",
    "total_portfolio_investment": "Inversión Total del Portafolio",
    "individual_opportunities": "Oportunidades de Inversión Individual",
    "lot_premium_frontage": "Lote - Frente Premium",
    "lot_size": "Tamaño",
    "buildable_sf": "SF Construible",
    "projected_roi": "ROI Proyectado",
    "lot_standard_frontage": "Lote - Frente Estándar",
    "fed_cuts_impact": "Impacto de los Recortes de Tasas del Fed en la Inversión en Almacén Seco",
    "financing_advantages": "Ventajas de Financiamiento",
    "lower_construction_rates": "Tasas de préstamo de construcción más bajas reducen los costos de mantenimiento",
    "better_dscr": "Mejores ratios de cobertura de servicio de deuda",
    "improved_cash_returns": "Retornos de efectivo sobre efectivo mejorados mediante apalancamiento",
    "refinancing_opportunities": "Oportunidades de refinanciamiento para desarrollos existentes",
    "market_movement": "Beneficios del Movimiento del Mercado",
    "increased_business": "Mayor actividad empresarial por menores costos de endeudamiento",
    "importers_expanding": "Más importadores expandiendo operaciones",
    "warehouse_demand": "Mayor demanda de espacio de almacén flexible",
    "optimal_timing": "Momento óptimo para nuevos proyectos de desarrollo",
    "complete_dry_portfolio": "Portafolio Completo de Almacén Seco",
    "total_acres_dry": "Acres Totales",
    "buildable_sf_dry": "SF Construible",
    "total_investment_dry": "Inversión Total",
    "annual_rental_income": "Ingreso Anual por Rentas",
    
    // Property Specifications
    "property_specifications": "Especificaciones de la Propiedad",
    "8_lots_available": "8 Lotes Industriales Premium Disponibles - Análisis Profesional de Suscripción",
    "premier_district": "Ubicado en el principal distrito industrial de McAllen con demanda logística probada. Datos corregidos muestran 44.17 acres totales, 585,530 SF construibles - significativamente más grande que lo indicado en los materiales de marketing.",
    "professional_analysis": "Análisis Profesional de Lotes Individuales",
    "lot_01_analysis": "Lote 01 - Análisis Profesional",
    "lot_coverage": "Cobertura del Lote",
    "land_investment": "Inversión en Terreno",
    "coverage_normal": "Dentro del rango normal",
    "per_acre": "por Acre",
    "per_buildable_sf": "por SF Construible",
    "plan_rent_sf": "Renta Plan/SF",
    "plan_vs_market": "Análisis de Renta Plan vs. Mercado",
    "plan_projection": "Proyección del Plan",
    "annual_noi": "NOI Anual",
    "upside": "upside",
    "strategic_advantages": "Ventajas Estratégicas",
    "direct_highway": "Acceso directo a la autopista desde Military Hwy",
    "strategic_industrial": "Ubicación industrial estratégica que mejora la visibilidad",
    "premium_corner": "Posición de esquina premium con doble frente",
    "risk_evaluation": "Evaluación de Riesgos",
    "verify_retention": "Verificar requisitos de estanque de retención y capacidad de servicios",
    "investment_recommendation": "Recomendación de Inversión",
    "positioning_strategy": "Estrategia de Posicionamiento: Ideal para una mezcla de inquilinos más pequeños con configuraciones de almacén flexibles.",
    "lot_02_analysis": "Lote 02 - Análisis Profesional",
    "improved_access": "Mejoras de acceso por nuevo desarrollo vial",
    "high_visibility": "Alta visibilidad de tráfico en corredor principal",
    "premium_frontage": "Ubicación premium con frente mejorado",
    "monitor_construction": "Monitorear el impacto del cronograma de construcción vial",
    "strong_dry_potential": "Fuerte potencial para almacén seco con beneficios de visibilidad.",
    "lot_03_analysis": "Lote 03 - Análisis Profesional",
    "largest_development": "Lote de desarrollo más grande disponible en el distrito",
    "maximum_potential": "Máximo potencial de desarrollo para inquilino ancla",
    "strategic_central": "Posición central estratégica con múltiples puntos de acceso",
    "ensure_circulation": "Asegurar circulación adecuada de camiones para operaciones a gran escala",
    "anchor_tenant_best": "Mejor para inquilino ancla de almacenamiento en frío o almacén seco grande.",
    "lot_04_analysis": "Lote 04 - Análisis Profesional",
    "future_expansion": "Listo para futura expansión con parcelas adyacentes",
    "optimized_utilities": "Servicios optimizados para desarrollo a gran escala",
    "distribution_potential": "Potencial de centro de distribución con acceso regional",
    "confirm_expansion": "Confirmar derechos de expansión y costos de actualización de servicios",
    "distribution_center": "Potencial de centro de distribución - ideal para instalación multi-inquilino.",
    "lot_05_analysis": "Lote 05 - Análisis Profesional",
    "premium_development": "Sitio de desarrollo premium con configuración óptima",
    "multiple_access": "Múltiples puntos de acceso para operaciones eficientes",
    "flexible_configuration": "Configuración flexible para varios tipos de inquilinos",
    "verify_parking": "Verificar requisitos de estacionamiento para configuración multi-inquilino",
    "premium_multi_tenant": "Oportunidad premium multi-inquilino con diseños flexibles.",
    "lot_06_analysis": "Lote 06 - Análisis Profesional",
    "value_positioning": "Posición de inversión de valor por debajo del promedio del distrito",
    "rapid_development": "Listo para desarrollo rápido con trabajo mínimo en el sitio",
    "strong_roi": "Fuerte potencial de ROI con rentas de mercado actuales",
    "investigate_pricing": "Investigar factores de precios por debajo del mercado",
    "value_play": "Juego de valor - alto potencial de ROI con desarrollo inmediato.",
    "lot_07_analysis": "Lote 07 - Análisis Profesional",
    "coverage_above": "Por encima del rango típico",
    "higher_density": "Mayor potencial de desarrollo de alta densidad en el portafolio",
    "exceptional_ratio": "Relación excepcional de SF por acre",
    "compact_site": "Sitio compacto maximiza la eficiencia del edificio",
    "high_density": "Alta densidad requiere planificación cuidadosa del sitio y circulación",
    "coverage_flag": "Bandera de Cobertura: Por encima del 65% - confirmar cumplimiento de zonificación",
    "specialized_warehouse": "Oportunidad de almacén especializado de alta densidad.",
    "lot_08_analysis": "Lote 08 - Análisis Profesional",
    "coverage_below": "Por debajo del rango eficiente",
    "largest_acreage": "Mayor superficie en el portafolio para futura expansión",
    "multiple_phases": "Posibles múltiples fases de desarrollo",
    "strategic_land": "Inversión en terreno estratégico con potencial de apreciación",
    "low_initial": "Baja densidad inicial de construcción - enfocarse en la apreciación del terreno",
    "coverage_flag_below": "Bandera de Cobertura: Por debajo del 20% - verificar restricciones del sitio",
    "premium_land": "Inversión en terreno premium con potencial de desarrollo futuro.",
    "portfolio_summary": "Resumen del Portafolio de 8 Lotes",
    "professional_underwriting": "Análisis profesional de suscripción - Distrito Industrial de McAllen, TX",
    "coverage_flags": "Banderas de Cobertura",
    "data_reconciliation": "Reconciliación de Datos vs. Materiales de Marketing",
    "marketing_indicated": "Indicado en Materiales de Marketing:",
    "verified_site_plan": "Verificado del Plano del Sitio:",
    "critical_correction": "Corrección Crítica Requerida:",
    "significantly_more": "El portafolio contiene significativamente más área desarrollable que la indicada en los materiales de marketing. Las superficies de los lotes 7 y 8 fueron transpuestas en los materiales originales.",
    "portfolio_noi": "Potencial de NOI del Portafolio (Anual)",
    "mixed_development": "Escenario de Desarrollo Mixto (Proyección del Plan): Varía",
    "all_dry_warehouse": "Todo Almacén Seco",
    "all_refrigerated": "Todo Almacén Refrigerado",
    "portfolio_strategies": "Estrategias de Inversión del Portafolio",
    "land_hold_strategy": "Estrategia de Retención de Terrenos",
    "lower_capital": "Menor requerimiento de capital inicial con un potencial de apreciación anual del 8-12%.",
    "dry_development": "Desarrollo de Almacén Seco",
    "stabilized_roi": "ROI estabilizado del 8.5-9.0% a través de la creación de valor y flujo de caja.",
    "refrigerated_development": "Desarrollo de Almacén Refrigerado",
    "cold_storage_roi": "ROI del 7.6-7.9% con prima de almacenamiento en frío especializado.",
    "professional_investment": "Análisis de Inversión Profesional",
    "comprehensive_analysis": "Análisis exhaustivo de estrategias de inversión, evaluación de riesgos y documentación de diligencia debida",
    "no_construction_risk": "Sin riesgo de construcción ni de arrendamiento de inquilinos",
    "flexibility_develop": "Flexibilidad para desarrollar o vender en el momento óptimo del mercado",
    "lower_capital_initial": "Menor requerimiento de capital inicial",
    "historical_performance": "Basado en el desempeño histórico de terrenos industriales premium",
    "risk_considerations": "Consideraciones de Riesgo",
    "no_immediate_income": "Sin generación de ingresos inmediata",
    "market_fluctuations": "Sujeto a fluctuaciones de apreciación del mercado",
    "carrying_costs": "Costos anuales de mantenimiento reducen los retornos netos",
    "immediate_income": "Generación de ingresos inmediata tras el arrendamiento",
    "higher_returns": "Mayores retornos a través de la creación de valor",
    "long_term_cash": "Flujo de caja a largo plazo de activos industriales de calidad",
    "value_added": "Valor agregado mediante mejoras operativas",
    "construction_cost_risk": "Riesgo de inflación de costos de construcción",
    "tenant_leasing": "Incertidumbre en el cronograma de arrendamiento de inquilinos",
    "market_rent": "Volatilidad de rentas de mercado durante el desarrollo",
    "premium_rents": "Rentas premium por almacenamiento en frío especializado",
    "strong_tenant": "Fuerte demanda de inquilinos de la industria de productos agrícolas",
    "high_barriers": "Altas barreras de entrada",
    "long_term_relationships": "Relaciones a largo plazo con inquilinos",
    "higher_complexity": "Mayor complejidad y costos de construcción",
    "specialized_equipment": "Requerimientos de mantenimiento de equipos especializados",
    "limited_tenant": "Grupo limitado de inquilinos para almacenamiento en frío",
    
    // Chat
    "chat_with_juan": "Conversa con Juan",
    
    // Navigation
    "home": "Inicio",
    "analysis": "Análisis",
    "chat": "Chat",
    "menu": "Menú",
    
    // Common
    "acres": "Acres",
    "close": "Cerrar",
    "million": "Millones",
    "sf": "SF",
    "view_details": "Ver Detalles",
    "contact_now": "Contactar Ahora",
    "learn_more": "Más Información"
  }
};