import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.overview': 'Overview',
    'nav.marketAnalysis': 'Market Analysis',
    'nav.landParcels': 'Land Parcels',
    'nav.virtualTour': 'Virtual Tour', 
    'nav.financials': 'Financials',
    'nav.properties': 'Properties',
    'nav.calculator': 'Calculator',
    
    // Hero Section
    'hero.badge': 'Fed Rate Cuts Drive Investment Opportunity • Historic Market Conditions',
    'hero.title': 'Prime Shovel-Ready Industrial Land Opportunities',
    'hero.description': 'Only 8 premium properties left in McAllen\'s premier industrial district on 10th Street. The Valley is America\'s hidden gem - those who invest here stay and grow. Following Fed rate adjustments, this presents strategic timing for positioned investors.',
    'hero.location': '10th Street • McAllen Industrial District • Heart of America\'s Produce Distribution Hub',
    'hero.marketVacancy': 'Market Vacancy (3Q24)',
    'hero.produceImports': 'TX Produce Imports',
    'hero.pricing': 'Per Acre Pricing',
    'hero.properties': 'Only Remaining',
    'hero.viewAnalysis': 'View Analysis',
    
    // Virtual Tour
    'virtualTour.title': 'MCC Industrial Park Virtual Tour',
    'virtualTour.subtitle': 'Virtual Property Tour',
    'virtualTour.description': 'Experience our premium industrial properties through immersive virtual tours.',
    
    // Market Insights
    'marketInsights.title': 'Market Insights & Analysis',
    'marketInsights.subtitle': 'Industry Expert Insights',
    'marketInsights.description': 'Stay informed with the latest market analysis and investment insights from industry leaders',
    
    // Executive Summary
    'executiveSummary.title': 'Executive Summary',
    'executiveSummary.subtitle': 'The Valley\'s Hidden Gem: A $13.25M land portfolio in America\'s most coveted industrial district',
    'executiveSummary.description': '43.17 acres of premium build-ready parcels on McAllen\'s 10th Street in the dynamic industrial growth market. Leverage Fed rate adjustments to strategically position in this compelling market where smart investors stay and grow.',
    'executiveSummary.opportunity': 'Strategic Investment Opportunity in McAllen',
    'executiveSummary.opportunityDesc': 'Only 8 properties available in McAllen\'s premier industrial district. Parcels on 10th Street corridor with ready utilities, industrial zoning, 585,530 SF buildable. The Valley\'s projected 20-year boom, combined with Fed rate cuts, creates unmatched appreciation potential. This market shows exceptional resilience to changing national conditions due to its unique demand drivers and limited supply.',
    'executiveSummary.portfolioValue': 'Land Portfolio Value',
    'executiveSummary.pricePerAcre': 'Price per Acre',
    'executiveSummary.valleyAdvantage': 'The Valley Advantage - America\'s Hidden Gem',
    'executiveSummary.premiumLocation': 'Premium Industrial Location: Strategic corner location on 10th Street with new road development',
    'executiveSummary.metroPopulation': '900K+ Metro Population: McAllen rivals El Paso size with strong growth trajectory',
    'executiveSummary.refrigeratedBoom': 'Refrigerated Industry Boom: Heart of produce alley with surging demand',
    'executiveSummary.fedTiming': 'Fed Rate Cut Timing: Perfect storm for development financing and appreciation',
    'executiveSummary.marketResilience': 'Market Resilience: Valley growth fundamentals provide stability amid changing national conditions',
    'executiveSummary.valleyOpportunity': 'Valley Investment Opportunity - Perfect Timing',
    'executiveSummary.whyInvestors': 'Why Investors Choose The Valley: Those who have done business in McAllen stay and grow - it\'s America\'s best-kept secret. Recent comparables show $281K/acre for ready sites, making our $250K-$300K pricing extremely attractive. Act Now to benefit from Fed rate cuts whether you build or hold. This represents a compelling investment opportunity with multiple favorable scenarios in a fundamentally strong market.',
    
    // Market Analysis
    'marketAnalysis.title': 'Market Analysis',
    'marketAnalysis.keyHighlights': 'Key Land Investment Highlights',
    'marketAnalysis.vacancy': 'Market vacancy (3Q24) supports stable occupancy in established market',
    'marketAnalysis.tradeVolume': 'Annual trade volume supports land demand with 44% growth projected',
    'marketAnalysis.rentalGrowth': 'Rental rate growth signals strong land appreciation potential',
    'marketAnalysis.buildableArea': 'Total buildable area across 44.17 premium acres - only 8 properties left',
    'marketAnalysis.strategicPosition': 'McAllen\'s Strategic Cross-Border Position',
    'marketAnalysis.strategicDesc': 'Located in McAllen\'s premier industrial district with proven produce/logistics demand. The Valley demonstrates market stability supported by cross-border trade through Pharr-Reynosa Bridge. Modeled under base and stress scenarios for lender confidence and investment clarity.',
    'marketAnalysis.dynamicTransformation': 'The Valley\'s Dynamic Market Transformation',
    'marketAnalysis.dynamicDesc': 'McAllen MSA Market Dynamics: Recent third-party reads show McAllen industrial vacancy around 3.9% (3Q24) with LTM rent growth ~1.9%–2.5%. Q2-2025 asking rents averaged $8.43/SF amid >1.3M SF under construction (CBRE Q2-2025). The Valley demonstrates consistent growth supported by cross-border trade with proven logistics demand patterns.',
    'marketAnalysis.vacancyTrend': 'Vacancy Rate Trend',
    'marketAnalysis.rentalRateGrowth': 'Rental Rate Growth',
    'marketAnalysis.tradeVolumeDistribution': 'Trade Volume Distribution',
    'marketAnalysis.tradeVolumeDesc': 'Over $6B annual produce trade through Pharr-Reynosa Bridge (~$47-$50B total trade) creates consistent demand for specialized cold storage and distribution facilities.',
    'marketAnalysis.avocados': 'Avocados',
    'marketAnalysis.berries': 'Berries',
    'marketAnalysis.peppers': 'Peppers',
    'marketAnalysis.onions': 'Onions',
    'marketAnalysis.others': 'Others',
    'marketAnalysis.supplyShortage': 'Supply Shortage - Current tenant demand vs limited available inventory',
    'marketAnalysis.importGrowth': 'Import Growth - Annual cross-border trade growth (Texas A&M Research)',
    'marketAnalysis.rentTrajectory': 'Rent Trajectory - Annual rental rate growth supported by market fundamentals',
    'marketAnalysis.onlyProperties': 'Only 8 Properties Left - McAllen\'s premier industrial opportunities',
    
    // Land Parcels
    'landParcels.title': 'Prime Land Development Opportunity',
    'landParcels.description': 'Raw land parcels available for development on Military Highway with prime agricultural fields ready for industrial conversion.',
    'landParcels.clickEnlarge': 'Click to Enlarge',
    'landParcels.militaryHighway': 'Military Highway Land Development',
    'landParcels.militaryDesc': 'Prime raw land parcels ready for industrial development with excellent highway access and build-to-suit potential',
    'landParcels.developmentReady': 'Development Ready - Build-to-Suit Available',
    'landParcels.portfolioInvestment': 'Portfolio Investment',
    'landParcels.totalBuildable': 'Total Buildable SF',
    'landParcels.avgPrice': 'Price Per Acre',
    'landParcels.totalAcres': 'Total Acres',
    'landParcels.location': '10th Street & Military Highway, McAllen, TX',
    'landParcels.stabilizedIncome': 'Stabilized Income Property',
    'landParcels.totalInvestment': 'Total Investment',
    'landParcels.totalSiteSize': 'Total Site Size',
    'landParcels.lotsBuildings': 'Lots Buildings',
    'landParcels.totalSF': 'Total',
    'landParcels.shovelReady': 'Shovel-Ready',
    'landParcels.avgRent': 'Average Rent NNN',
    'landParcels.appreciation': 'Appreciation',
    'landParcels.capRate': 'Cap Rate',
    'landParcels.propertyFeatures': 'Property Features',
    'landParcels.shovelReadyLots': 'Shovel-ready development lots',
    'landParcels.industrialZoning': 'Industrial zoning approved',
    'landParcels.utilities': 'Utilities to site boundaries',
    'landParcels.borderLocation': 'Strategic border location',
    'landParcels.highwayAccess': 'Prime highway access',
    'landParcels.investmentHighlights': 'Investment Highlights',
    'landParcels.yearBuilt': 'Year Built:',
    'landParcels.immediateDev': 'Immediate Development',
    'landParcels.occupancy': 'Occupancy:',
    'landParcels.developmentReady2': 'Development Ready',
    'landParcels.annualNOI': 'Annual NOI:',
    'landParcels.landInvestment': 'Land Investment',
    'landParcels.investmentSummary': 'Investment Summary',
    'landParcels.summaryDesc': 'Stabilized industrial park with excellent tenant mix, modern facilities, and sustainable energy features generating strong cash flow.',
    'landParcels.keyAdvantages': 'Key Advantages',
    'landParcels.immediateCashFlow': 'Immediate cash flow from day one',
    'landParcels.creditTenants': 'Credit tenants with long-term leases',
    'landParcels.primeLocation': 'Prime Military Highway location',
    'landParcels.onSiteManagement': 'Professional on-site management',
    'landParcels.transportAccess': 'Excellent transportation access',
    'landParcels.financialPerformance': 'Financial Performance',
    'landParcels.stabilizedCap': '8.5% stabilized cap rate',
    'landParcels.annualNOI2': '$3.89M annual net operating income',
    'landParcels.occupancyRate': '95% occupancy with quality tenants',
    'landParcels.rentEscalations': 'Built-in rent escalations',
    'landParcels.valueAdd': 'Value-add potential through expansions',
    
    // Individual Lots
    'individualLots.title': 'Individual Lot Analysis',
    'individualLots.subtitle': '8 strategically positioned lots at 10th Street & Military Highway intersection, McAllen, Texas',
    'individualLots.totalAcres': 'Total Acres',
    'individualLots.totalBuildable': 'Total Buildable',
    'individualLots.portfolioInvestment': 'Portfolio Investment',
    'individualLots.avgPrice': 'Avg Price/Acre',
    'individualLots.landInvestment': 'Land Investment',
    'individualLots.buildableSF': 'Buildable SF',
    'individualLots.dryWarehouseROI': 'Dry Warehouse ROI',
    'individualLots.refrigeratedROI': 'Refrigerated ROI',
    'individualLots.dryWarehouseDev': 'Dry Warehouse Development',
    'individualLots.refrigeratedDev': 'Refrigerated Development',
    'individualLots.constructionCost': 'Construction Cost:',
    'individualLots.totalInvestment': 'Total Investment:',
    'individualLots.annualNOI': 'Annual NOI:',
    'individualLots.projectedROI': 'Projected ROI:',
    
    // Lot Descriptions
    'individualLots.lot1Title': 'Lot 1 - Premium Corner Position',
    'individualLots.lot1Desc': 'Corner lot with dual Military Highway and 10th Street frontage',
    'individualLots.lot2Title': 'Lot 2 - Flexible Development Site',
    'individualLots.lot2Desc': 'Excellent truck circulation potential, multi-tenant ready',
    'individualLots.lot3Title': 'Lot 3 - High-Capacity Development',
    'individualLots.lot3Desc': 'Larger development capacity, optimal for anchor tenant',
    'individualLots.lot4Title': 'Lot 4 - Distribution Hub Potential',
    'individualLots.lot4Desc': 'Prime for cross-dock operations, regional distribution center',
    'individualLots.lot5Title': 'Lot 5 - Multi-Tenant Configuration',
    'individualLots.lot5Desc': 'Flexible site layout, multi-tenant industrial park ready',
    'individualLots.lot6Title': 'Lot 6 - Value Investment Position',
    'individualLots.lot6Desc': 'Strong development density, excellent ROI potential',
    'individualLots.lot7Title': 'Lot 7 - High-Density Development Site',
    'individualLots.lot7Desc': 'Compact site with exceptional development density potential',
    'individualLots.lot8Title': 'Lot 8 - Premium Large Development Opportunity',
    'individualLots.lot8Desc': 'Large acreage site ideal for future expansion and development',
    
    // Strategic Location & Fed Rate Impact
    'strategic.fedRateImpact': 'Fed Rate Cuts Impact on Dry Warehouse Investment',
    'strategic.financingAdvantages': 'Financing Advantages',
    'strategic.lowerConstructionRates': 'Lower construction loan rates reduce carrying costs',
    'strategic.improvedCoverage': 'Improved debt service coverage ratios',
    'strategic.enhancedReturns': 'Enhanced cash-on-cash returns through leverage',
    'strategic.refinancingOpps': 'Refinancing opportunities for existing developments',
    'strategic.marketMovementBenefits': 'Market Movement Benefits',
    'strategic.increasedActivity': 'Increased business activity from lower borrowing costs',
    'strategic.expandingImporters': 'More importers expanding operations',
    'strategic.higherDemand': 'Higher demand for flexible warehouse space',
    'strategic.optimalTiming': 'Optimal timing for new development projects',
    'strategic.completePortfolio': 'Complete Dry Warehouse Portfolio',
    'strategic.totalAcres': 'Total Acres',
    'strategic.buildableSqFt': 'Buildable Sq Ft',
    'strategic.totalInvestment': 'Total Investment',
    'strategic.annualRental': 'Annual Rental Income',
    'strategic.locationConnectivity': 'Strategic Location & Connectivity',
    'strategic.locationDesc': 'Prime positioning adjacent to McAllen South Industrial Park with direct access to major international bridges and trade corridors',
    'strategic.keyDistances': 'Key Distances',
    'strategic.ih2Interstate': 'IH-2 Interstate',
    'strategic.tollRoad': '365 Toll Road',
    'strategic.anzalduasBridge': 'Anzalduas Bridge',
    'strategic.mcallenBridge': 'McAllen-Hidalgo Bridge',
    'strategic.pharrBridge': 'Pharr-Reynosa Bridge',
    'strategic.borderLocation': 'Strategic Border Location',
    'strategic.borderDesc': 'Adjacent to McAllen South Industrial Park with access to three major international bridges',
    'strategic.texasProduce': 'of Texas fresh produce imports',
    'strategic.transportInfra': 'Transportation Infrastructure',
    'strategic.militaryHighwayDesc': 'Military Highway (FM 1016) provides seamless connectivity to major distribution networks',
    'strategic.truckloadsAnnually': 'truckloads annually',
    'strategic.crossBorderHub': 'Cross-Border Trade Hub',
    'strategic.gatewayDesc': 'Gateway to $6B+ annual produce trade through Pharr-Reynosa Bridge (~$47-$50B total trade)',
    'strategic.importsValue': '2024 imports',
    'strategic.utilityInfra': 'Utility Infrastructure',
    'strategic.utilityDesc': 'Established industrial utilities with capacity for large-scale warehouse development',
    'strategic.shovelReady': 'Shovel-ready sites',
    'strategic.laborMarket': 'Labor Market Access',
    'strategic.laborDesc': 'Access to 145,000+ manufacturing employees in the Rio Grande Valley region',
    'strategic.workers': 'workers',
    'strategic.devEcosystem': 'Development Ecosystem',
    'strategic.ecosystemDesc': 'Established network of cold storage specialists and food processing facilities',
    'strategic.provenMarket': 'Proven market',
    'strategic.economicImpact': 'Economic Impact & Growth Drivers',
    'strategic.regionalRetail': 'Regional Retail Trade',
    'strategic.populationGrowth': 'Population Growth (2012-2022)',
    'strategic.ecommerceGrowth': 'E-commerce Grocery Growth',
    'strategic.dailyTrucks': 'Daily Produce Trucks',
    'strategic.militaryCorridor': 'Military Highway (FM 1016) Corridor',
    'strategic.corridorDesc': 'Strategically located along the primary industrial transportation artery connecting McAllen to the Pharr-Reynosa International Bridge, providing seamless access to Mexico\'s growing produce export economy and North American distribution networks.',
    'strategic.minutesFromBridge': 'Minutes from Pharr-Reynosa International Bridge',
    
    // News Items
    'news.fedRates': 'Fed Could Cut Rates to at Least 3%, Says Bank of America\'s Cabana',
    'news.fedRatesDesc': '36K views • 4 days ago - Expert analysis on Federal Reserve rate cuts and their impact on real estate investments.',
    'news.interestRates': 'How Will Interest Rate Cuts Impact? | Today | Telemundo',
    'news.interestRatesDesc': 'Analysis on how rate cuts will affect real estate investments and market opportunities.',
    'news.fedEnvironment': 'Analysis of Fed Rate Environment and Its Impact on Commercial Real Estate',
    'news.fedEnvironmentDesc': 'Expert insights on rate changes and real estate investment strategies.',
    'news.powellAnalysis': 'Everything Fed Chair Powell Did \'TOO LATE\' Revealed',
    'news.powellAnalysisDesc': '1 day ago - Critical analysis of Federal Reserve decisions affecting commercial real estate markets.',

    // Demographics & Market Profile
    'demographics.title': 'Area Demographics & Market Profile',
    'demographics.subtitle': 'Strategic positioning in a growing market with strong economic fundamentals and expanding population base',
    'demographics.marketDemographics': 'Market Demographics',
    'demographics.population': 'Population',
    'demographics.avgHouseholdIncome': 'Avg Household Income',
    'demographics.avgAge': 'Average Age',
    'demographics.avgHouseValue': 'Avg House Value',
    'demographics.marketProfileTitle': 'Current Market Demographics',
    'demographics.marketProfileDescription': 'The 5-mile demographic profile demonstrates a young, growing workforce with increasing household incomes, creating strong demand for distribution and logistics services in today\'s booming Valley market.',
    'demographics.primeWorkingPopulation': 'Average Age - Prime Working Population',
    'demographics.strongConsumerBase': 'Household Income - Strong Consumer Base',
    'demographics.establishedCommunity': 'Home Value - Established Community',

    // Strategic Industrial Ecosystem
    'strategic.ecosystemTitle': 'Strategic Industrial Ecosystem',
    'strategic.ecosystemSubtitle': 'Located in the heart of McAllen\'s industrial corridor with direct access to key trade and logistics infrastructure',
    'strategic.primePositioning': 'Prime Industrial Positioning',
    'strategic.positioningDescription': 'The site\'s strategic location adjacent to the McAllen South Industrial Park development positions it at the center of the region\'s most dynamic industrial growth area, with established infrastructure and proven demand from major logistics operators.',
    'strategic.mcallenForeignTradeZone': 'McAllen Foreign Trade Zone',
    'strategic.dutyFreeProcessing': 'Duty-free processing and warehousing',
    'strategic.mcallenProduceTerminal': 'McAllen Produce Terminal',
    'strategic.produceDistributionHub': 'Major regional produce distribution hub',
    'strategic.majesticTradingPort': 'Majestic International Trading Port',
    'strategic.crossBorderLogistics': 'Cross-border logistics facility',
    'strategic.competitiveAdvantages': 'Competitive Advantages',
    'strategic.militaryHighwayFrontage': 'Military Highway frontage with high visibility and truck accessibility',
    'strategic.establishedCorridor': 'Established industrial corridor with proven tenant demand',
    'strategic.proximityBridges': 'Proximity to three international bridges for diversified trade access',
    'strategic.infrastructureReady': 'Infrastructure-ready sites eliminate development delays and costs',

    // Property Specifications
    'properties.title': 'Property Specifications',
    'properties.premiumLots': '8 Premium Industrial Lots Available',
    'properties.professionalAnalysis': 'Professional Underwriting Analysis',
    'properties.locationDescription': 'Located in McAllen\'s premier industrial district with proven logistics demand.',
    'properties.correctedData': 'Corrected data',
    'properties.significantlyLarger': 'significantly larger than marketing materials indicated',
    'properties.aerialView': 'Aerial View - Military Highway Development',
    'properties.siteBlueprint': 'Detailed Site Plan Blueprint',

    // Professional Underwriting
    'underwriting.professionalAnalysis': 'Professional Analysis',
    'underwriting.location': '10th St & Military Hwy, McAllen Industrial District',
    'underwriting.landInvestment': 'Land Investment',
    'underwriting.siteCoverage': 'Site Coverage',
    'underwriting.withinNormalRange': 'Within normal range',
    'underwriting.aboveTypicalRange': 'Above typical range',
    'underwriting.belowEfficientRange': 'Below efficient range',
    'underwriting.landPerAcre': 'Land $/Acre',
    'underwriting.perAcreBasis': 'Per acre basis',
    'underwriting.landPerSF': 'Land $/SF',
    'underwriting.perBuildableSF': 'Per buildable SF',
    'underwriting.planRentSF': 'Plan Rent/SF',
    'underwriting.impliedFromPlan': 'Implied from plan',
    'underwriting.planMarketAnalysis': 'Plan vs. Market-Rate Analysis',
    'underwriting.scenario': 'Scenario',
    'underwriting.rentSF': 'Rent/SF',
    'underwriting.annualNOI': 'Annual NOI',
    'underwriting.vsPlan': 'vs Plan',
    'underwriting.planProjection': 'Plan Projection',
    'underwriting.dryWarehouse12': 'Dry Warehouse ($12/SF)',
    'underwriting.dryWarehouse125': 'Dry Warehouse ($12.50/SF)',
    'underwriting.coldStorage18': 'Cold Storage ($18/SF)',
    'underwriting.upside': 'upside',
    'underwriting.strategicAdvantages': 'Strategic Advantages',
    'underwriting.riskAssessment': 'Risk Assessment',
    'underwriting.coverageFlag': 'Coverage Flag',
    'underwriting.below20Verify': 'Below 20% - verify site constraints',
    'underwriting.above65Confirm': 'Above 65% - confirm zoning compliance',
    'underwriting.investmentRecommendation': 'Investment Recommendation',
    'underwriting.positioningStrategy': 'Positioning Strategy:',
    'underwriting.exportTearSheet': 'Export Tear Sheet',
    'underwriting.runScenarios': 'Run Scenarios'
  },
  es: {
    // Navigation
    'nav.overview': 'Resumen',
    'nav.marketAnalysis': 'Análisis de Mercado',
    'nav.landParcels': 'Parcelas de Terreno',
    'nav.virtualTour': 'Tour Virtual',
    'nav.financials': 'Financieros',
    'nav.properties': 'Propiedades',
    'nav.calculator': 'Calculadora',
    
    // Hero Section
    'hero.badge': 'Recortes de Tasas del Fed Impulsan Oportunidad de Inversión • Condiciones Históricas del Mercado',
    'hero.title': 'Oportunidades de Terreno Industrial Premium Listo para Construir',
    'hero.description': 'Solo quedan 8 propiedades premium en el distrito industrial principal de McAllen en la calle 10. El Valle es la joya oculta de América - quienes invierten aquí se quedan y crecen. Siguiendo los ajustes de tasas del Fed, esto presenta un momento estratégico para inversionistas posicionados.',
    'hero.location': 'Calle 10 • Distrito Industrial de McAllen • Corazón del Centro de Distribución de Productos de América',
    'hero.marketVacancy': 'Vacancia del Mercado (3T24)',
    'hero.produceImports': 'Importaciones de Productos TX',
    'hero.pricing': 'Precio por Acre',
    'hero.properties': 'Solo Restantes',
    'hero.viewAnalysis': 'Ver Análisis',
    
    // Virtual Tour
    'virtualTour.title': 'Tour Virtual del Parque Industrial MCC',
    'virtualTour.subtitle': 'Tour Virtual de Propiedades',
    'virtualTour.description': 'Experimenta nuestras propiedades industriales premium a través de recorridos virtuales inmersivos.',
    
    // Market Insights
    'marketInsights.title': 'Perspectivas y Análisis del Mercado',
    'marketInsights.subtitle': 'Perspectivas de Expertos de la Industria',
    'marketInsights.description': 'Mantente informado con el análisis de mercado más reciente y perspectivas de inversión de líderes de la industria',
    
    // Executive Summary  
    'executiveSummary.title': 'Resumen Ejecutivo',
    'executiveSummary.subtitle': 'La Joya Oculta del Valle: Un portafolio de terrenos de $12.24M en el distrito industrial más codiciado de América',
    'executiveSummary.description': '44.17 acres de parcelas premium listas para construir en la calle 10 de McAllen, en el dinámico mercado de crecimiento industrial. Aprovecha los ajustes de tasas del Fed para posicionarte estratégicamente en este atractivo mercado donde los inversionistas inteligentes permanecen y crecen.',
    'executiveSummary.opportunity': 'Oportunidad de Inversión Estratégica en McAllen',
    'executiveSummary.opportunityDesc': 'Solo 8 propiedades disponibles en el principal distrito industrial de McAllen. Parcelas en el corredor de la calle 10 con servicios listos, zonificación industrial, 585,530 SF construibles. El auge proyectado de 20 años del Valle, combinado con recortes de tasas del Fed, crea un potencial de apreciación inigualable. Este mercado muestra una resiliencia excepcional frente a condiciones nacionales cambiantes debido a sus únicos impulsores de demanda y oferta limitada.',
    'executiveSummary.portfolioValue': 'Valor del Portafolio de Terrenos',
    'executiveSummary.pricePerAcre': 'Precio por Acre',
    'executiveSummary.valleyAdvantage': 'La Ventaja del Valle - La Joya Oculta de América',
    'executiveSummary.premiumLocation': 'Ubicación Industrial Premium: Ubicación estratégica en esquina en la calle 10 con nuevo desarrollo vial',
    'executiveSummary.metroPopulation': 'Población Metropolitana de 900K+: McAllen rivaliza con el tamaño de El Paso con una sólida trayectoria de crecimiento',
    'executiveSummary.refrigeratedBoom': 'Auge de la Industria Refrigerada: Corazón del corredor de productos con demanda creciente',
    'executiveSummary.fedTiming': 'Momento de Recortes del Fed: Tormenta perfecta para financiamiento de desarrollo y apreciación',
    'executiveSummary.marketResilience': 'Resistencia del Mercado: Los fundamentos de crecimiento del Valle proporcionan estabilidad en medio de condiciones nacionales cambiantes',
    'executiveSummary.valleyOpportunity': 'Oportunidad de Inversión del Valle - Momento Perfecto',
    'executiveSummary.whyInvestors': 'Por Qué los Inversionistas Eligen el Valle: Aquellos que han hecho negocios en McAllen se quedan y crecen - es el secreto mejor guardado de América. Comparables recientes muestran $281K/acre para sitios listos, haciendo que nuestros precios de $250K-$300K sean extremadamente atractivos. Actúa Ahora para beneficiarte de los recortes de tasas del Fed ya sea que construyas o mantengas. Esto representa una oportunidad de inversión convincente con múltiples escenarios favorables en un mercado fundamentalmente sólido.',
    
    // Market Analysis
    'marketAnalysis.title': 'Análisis de Mercado',
    'marketAnalysis.keyHighlights': 'Aspectos Destacados de la Inversión en Terrenos',
    'marketAnalysis.vacancy': 'La vacancia del mercado (3T24) respalda la ocupación estable en el mercado establecido',
    'marketAnalysis.tradeVolume': 'El volumen de comercio anual respalda la demanda de terrenos con un crecimiento proyectado del 44%',
    'marketAnalysis.rentalGrowth': 'El crecimiento de las tarifas de alquiler señala un fuerte potencial de apreciación del terreno',
    'marketAnalysis.buildableArea': 'Área total construible en 44.17 acres premium - solo quedan 8 propiedades',
    'marketAnalysis.strategicPosition': 'Posición Estratégica Transfronteriza de McAllen',
    'marketAnalysis.strategicDesc': 'Ubicado en el distrito industrial premier de McAllen con demanda comprobada de productos/logística. El Valle demuestra estabilidad del mercado respaldada por el comercio transfronterizo a través del Puente Pharr-Reynosa. Modelado bajo escenarios base y de estrés para confianza del prestamista y claridad de inversión.',
    'marketAnalysis.dynamicTransformation': 'La Transformación Dinámica del Mercado del Valle',
    'marketAnalysis.dynamicDesc': 'Dinámicas del Mercado MSA de McAllen: Lecturas recientes de terceros muestran una vacancia industrial de McAllen alrededor del 3.9% (3T24) con crecimiento de alquileres LTM ~1.9%–2.5%. Los alquileres solicitados en Q2-2025 promediaron $8.43/SF en medio de >1.3M SF en construcción (CBRE Q2-2025). El Valle demuestra crecimiento consistente respaldado por comercio transfronterizo con patrones de demanda logística comprobados.',
    'marketAnalysis.vacancyTrend': 'Tendencia de Tasa de Vacancia',
    'marketAnalysis.rentalRateGrowth': 'Crecimiento de Tasa de Alquiler',
    'marketAnalysis.tradeVolumeDistribution': 'Distribución del Volumen de Comercio',
    'marketAnalysis.tradeVolumeDesc': 'Más de $6B de comercio anual de productos a través del Puente Pharr-Reynosa (~$47-$50B de comercio total) crea demanda consistente para instalaciones especializadas de almacenamiento en frío y distribución.',
    'marketAnalysis.avocados': 'Aguacates',
    'marketAnalysis.berries': 'Bayas',
    'marketAnalysis.peppers': 'Pimientos',
    'marketAnalysis.onions': 'Cebollas',
    'marketAnalysis.others': 'Otros',
    'marketAnalysis.supplyShortage': 'Escasez de Suministro - Demanda actual de inquilinos vs inventario disponible limitado',
    'marketAnalysis.importGrowth': 'Crecimiento de Importaciones - Crecimiento anual del comercio transfronterizo (Investigación de Texas A&M)',
    'marketAnalysis.rentTrajectory': 'Trayectoria de Alquiler - Crecimiento anual de tasas de alquiler respaldado por fundamentos del mercado',
    'marketAnalysis.onlyProperties': 'Solo Quedan 8 Propiedades - Oportunidades industriales premier de McAllen',
    
    // Land Parcels
    'landParcels.title': 'Oportunidad de Desarrollo de Terreno Premium',
    'landParcels.description': 'Parcelas de terreno sin desarrollar disponibles para desarrollo en Military Highway con campos agrícolas premium listos para conversión industrial.',
    'landParcels.clickEnlarge': 'Clic para Ampliar',
    'landParcels.militaryHighway': 'Desarrollo de Terreno en Military Highway',
    'landParcels.militaryDesc': 'Parcelas de terreno premium listas para desarrollo industrial con excelente acceso a carretera y potencial para construcción personalizada',
    'landParcels.developmentReady': 'Listo para Desarrollo - Construcción Personalizada Disponible',
    'landParcels.portfolioInvestment': 'Inversión del Portafolio',
    'landParcels.totalBuildable': 'Total de SF Construibles',
    'landParcels.avgPrice': 'Precio por Acre',
    'landParcels.totalAcres': 'Total de Acres',
    'landParcels.location': 'Calle 10 y Military Highway, McAllen, TX',
    'landParcels.stabilizedIncome': 'Propiedad de Ingresos Estabilizada',
    'landParcels.totalInvestment': 'Inversión Total',
    'landParcels.totalSiteSize': 'Tamaño Total del Sitio',
    'landParcels.lotsBuildings': 'Edificios de Lotes',
    'landParcels.totalSF': 'Total',
    'landParcels.shovelReady': 'Listo para Construir',
    'landParcels.avgRent': 'Alquiler Promedio NNN',
    'landParcels.appreciation': 'Apreciación',
    'landParcels.capRate': 'Tasa de Capitalización',
    'landParcels.propertyFeatures': 'Características de la Propiedad',
    'landParcels.shovelReadyLots': 'Lotes de desarrollo listos para construir',
    'landParcels.industrialZoning': 'Zonificación industrial aprobada',
    'landParcels.utilities': 'Servicios públicos hasta los límites del sitio',
    'landParcels.borderLocation': 'Ubicación fronteriza estratégica',
    'landParcels.highwayAccess': 'Acceso premium a carretera',
    'landParcels.investmentHighlights': 'Aspectos Destacados de la Inversión',
    'landParcels.yearBuilt': 'Año de Construcción:',
    'landParcels.immediateDev': 'Desarrollo Inmediato',
    'landParcels.occupancy': 'Ocupación:',
    'landParcels.developmentReady2': 'Listo para Desarrollo',
    'landParcels.annualNOI': 'NOI Anual:',
    'landParcels.landInvestment': 'Inversión en Terreno',
    'landParcels.investmentSummary': 'Resumen de Inversión',
    'landParcels.summaryDesc': 'Parque industrial estabilizado con excelente mezcla de inquilinos, instalaciones modernas y características de energía sostenible que generan un fuerte flujo de efectivo.',
    'landParcels.keyAdvantages': 'Ventajas Clave',
    'landParcels.immediateCashFlow': 'Flujo de efectivo inmediato desde el primer día',
    'landParcels.creditTenants': 'Inquilinos con crédito con contratos a largo plazo',
    'landParcels.primeLocation': 'Ubicación premium en Military Highway',
    'landParcels.onSiteManagement': 'Gestión profesional en el sitio',
    'landParcels.transportAccess': 'Excelente acceso al transporte',
    'landParcels.financialPerformance': 'Rendimiento Financiero',
    'landParcels.stabilizedCap': '8.5% tasa de capitalización estabilizada',
    'landParcels.annualNOI2': '$3.89M de ingresos operativos netos anuales',
    'landParcels.occupancyRate': '95% de ocupación con inquilinos de calidad',
    'landParcels.rentEscalations': 'Escalaciones de alquiler incorporadas',
    'landParcels.valueAdd': 'Potencial de valor agregado a través de expansiones',
    
    // Individual Lots
    'individualLots.title': 'Análisis de Lotes Individuales',
    'individualLots.subtitle': '8 lotes posicionados estratégicamente en la intersección de la Calle 10 y Military Highway, McAllen, Texas',
    'individualLots.totalAcres': 'Total de Acres',
    'individualLots.totalBuildable': 'Total Construible',
    'individualLots.portfolioInvestment': 'Inversión del Portafolio',
    'individualLots.avgPrice': 'Precio Promedio/Acre',
    'individualLots.landInvestment': 'Inversión en Terreno',
    'individualLots.buildableSF': 'SF Construibles',
    'individualLots.dryWarehouseROI': 'ROI Almacén Seco',
    'individualLots.refrigeratedROI': 'ROI Refrigerado',
    'individualLots.dryWarehouseDev': 'Desarrollo de Almacén Seco',
    'individualLots.refrigeratedDev': 'Desarrollo Refrigerado',
    'individualLots.constructionCost': 'Costo de Construcción:',
    'individualLots.totalInvestment': 'Inversión Total:',
    'individualLots.annualNOI': 'NOI Anual:',
    'individualLots.projectedROI': 'ROI Proyectado:',
    
    // Lot Descriptions
    'individualLots.lot1Title': 'Lote 1 - Posición Premium en Esquina',
    'individualLots.lot1Desc': 'Lote en esquina con frente dual a Military Highway y Calle 10',
    'individualLots.lot2Title': 'Lote 2 - Sitio de Desarrollo Flexible',
    'individualLots.lot2Desc': 'Excelente potencial de circulación de camiones, listo para múltiples inquilinos',
    'individualLots.lot3Title': 'Lote 3 - Desarrollo de Alta Capacidad',
    'individualLots.lot3Desc': 'Mayor capacidad de desarrollo, óptimo para inquilino ancla',
    'individualLots.lot4Title': 'Lote 4 - Potencial de Centro de Distribución',
    'individualLots.lot4Desc': 'Premium para operaciones de cross-dock, centro de distribución regional',
    'individualLots.lot5Title': 'Lote 5 - Configuración Multi-Inquilino',
    'individualLots.lot5Desc': 'Diseño de sitio flexible, parque industrial multi-inquilino listo',
    'individualLots.lot6Title': 'Lote 6 - Posición de Inversión de Valor',
    'individualLots.lot6Desc': 'Fuerte densidad de desarrollo, excelente potencial de ROI',
    'individualLots.lot7Title': 'Lote 7 - Sitio de Desarrollo de Alta Densidad',
    'individualLots.lot7Desc': 'Sitio compacto con potencial excepcional de densidad de desarrollo',
    'individualLots.lot8Title': 'Lote 8 - Oportunidad de Desarrollo Grande Premium',
    'individualLots.lot8Desc': 'Sitio de gran superficie ideal para futura expansión y desarrollo',
    
    // Strategic Location & Fed Rate Impact
    'strategic.fedRateImpact': 'Impacto de los Recortes de Tasas del Fed en la Inversión de Almacén Seco',
    'strategic.financingAdvantages': 'Ventajas de Financiamiento',
    'strategic.lowerConstructionRates': 'Las tasas más bajas de préstamos de construcción reducen los costos de mantenimiento',
    'strategic.improvedCoverage': 'Ratios mejorados de cobertura del servicio de deuda',
    'strategic.enhancedReturns': 'Retornos mejorados de efectivo sobre efectivo a través del apalancamiento',
    'strategic.refinancingOpps': 'Oportunidades de refinanciamiento para desarrollos existentes',
    'strategic.marketMovementBenefits': 'Beneficios del Movimiento del Mercado',
    'strategic.increasedActivity': 'Mayor actividad comercial por menores costos de endeudamiento',
    'strategic.expandingImporters': 'Más importadores expandiendo operaciones',
    'strategic.higherDemand': 'Mayor demanda de espacio de almacén flexible',
    'strategic.optimalTiming': 'Momento óptimo para nuevos proyectos de desarrollo',
    'strategic.completePortfolio': 'Portafolio Completo de Almacén Seco',
    'strategic.totalAcres': 'Total de Acres',
    'strategic.buildableSqFt': 'Pies Cuadrados Construibles',
    'strategic.totalInvestment': 'Inversión Total',
    'strategic.annualRental': 'Ingresos de Alquiler Anual',
    'strategic.locationConnectivity': 'Ubicación Estratégica y Conectividad',
    'strategic.locationDesc': 'Posicionamiento premium adyacente al Parque Industrial McAllen Sur con acceso directo a los principales puentes internacionales y corredores comerciales',
    'strategic.keyDistances': 'Distancias Clave',
    'strategic.ih2Interstate': 'Interestatal IH-2',
    'strategic.tollRoad': 'Carretera de Peaje 365',
    'strategic.anzalduasBridge': 'Puente Anzalduas',
    'strategic.mcallenBridge': 'Puente McAllen-Hidalgo',
    'strategic.pharrBridge': 'Puente Pharr-Reynosa',
    'strategic.borderLocation': 'Ubicación Fronteriza Estratégica',
    'strategic.borderDesc': 'Adyacente al Parque Industrial McAllen Sur con acceso a tres puentes internacionales principales',
    'strategic.texasProduce': 'de las importaciones de productos frescos de Texas',
    'strategic.transportInfra': 'Infraestructura de Transporte',
    'strategic.militaryHighwayDesc': 'Military Highway (FM 1016) proporciona conectividad perfecta a las principales redes de distribución',
    'strategic.truckloadsAnnually': 'cargas de camión anualmente',
    'strategic.crossBorderHub': 'Centro de Comercio Transfronterizo',
    'strategic.gatewayDesc': 'Puerta de entrada a más de $6B de comercio anual de productos a través del Puente Pharr-Reynosa (~$47-$50B de comercio total)',
    'strategic.importsValue': 'importaciones 2024',
    'strategic.utilityInfra': 'Infraestructura de Servicios Públicos',
    'strategic.utilityDesc': 'Servicios públicos industriales establecidos con capacidad para desarrollo de almacenes a gran escala',
    'strategic.shovelReady': 'Sitios listos para construir',
    'strategic.laborMarket': 'Acceso al Mercado Laboral',
    'strategic.laborDesc': 'Acceso a más de 145,000 empleados de manufactura en la región del Valle del Río Grande',
    'strategic.workers': 'trabajadores',
    'strategic.devEcosystem': 'Ecosistema de Desarrollo',
    'strategic.ecosystemDesc': 'Red establecida de especialistas en almacenamiento en frío e instalaciones de procesamiento de alimentos',
    'strategic.provenMarket': 'Mercado comprobado',
    'strategic.economicImpact': 'Impacto Económico e Impulsores de Crecimiento',
    'strategic.regionalRetail': 'Comercio Minorista Regional',
    'strategic.populationGrowth': 'Crecimiento Poblacional (2012-2022)',
    'strategic.ecommerceGrowth': 'Crecimiento de Comercio Electrónico de Comestibles',
    'strategic.dailyTrucks': 'Camiones Diarios de Productos',
    'strategic.militaryCorridor': 'Corredor de Military Highway (FM 1016)',
    'strategic.corridorDesc': 'Ubicado estratégicamente a lo largo de la arteria de transporte industrial principal que conecta McAllen con el Puente Internacional Pharr-Reynosa, proporcionando acceso perfecto a la creciente economía de exportación de productos de México y las redes de distribución de América del Norte.',
    'strategic.minutesFromBridge': 'Minutos del Puente Internacional Pharr-Reynosa',
    
    // Demographics & Market Profile
    'demographics.title': 'Demografía del Área y Perfil del Mercado',
    'demographics.subtitle': 'Posicionamiento estratégico en un mercado en crecimiento con fundamentos económicos sólidos y base poblacional en expansión',
    'demographics.marketDemographics': 'Demografía del Mercado',
    'demographics.population': 'Población',
    'demographics.avgHouseholdIncome': 'Ingreso Promedio del Hogar',
    'demographics.avgAge': 'Edad Promedio',
    'demographics.avgHouseValue': 'Valor Promedio de Vivienda',
    'demographics.marketProfileTitle': 'Demografía Actual del Mercado',
    'demographics.marketProfileDescription': 'El perfil demográfico de 5 millas demuestra una fuerza laboral joven y en crecimiento con ingresos familiares crecientes, creando una fuerte demanda de servicios de distribución y logística en el próspero mercado actual del Valle.',
    'demographics.primeWorkingPopulation': 'Edad Promedio - Población en Edad Laboral Óptima',
    'demographics.strongConsumerBase': 'Ingreso Familiar - Base de Consumidores Sólida',
    'demographics.establishedCommunity': 'Valor de Vivienda - Comunidad Establecida',

    // Strategic Industrial Ecosystem
    'strategic.ecosystemTitle': 'Ecosistema Industrial Estratégico',
    'strategic.ecosystemSubtitle': 'Ubicado en el corazón del corredor industrial de McAllen con acceso directo a infraestructura clave de comercio y logística',
    'strategic.primePositioning': 'Posicionamiento Industrial Principal',
    'strategic.positioningDescription': 'La ubicación estratégica del sitio adyacente al desarrollo del Parque Industrial South de McAllen lo posiciona en el centro del área de crecimiento industrial más dinámico de la región, con infraestructura establecida y demanda comprobada de operadores logísticos importantes.',
    'strategic.mcallenForeignTradeZone': 'Zona de Comercio Exterior de McAllen',
    'strategic.dutyFreeProcessing': 'Procesamiento y almacenamiento libre de aranceles',
    'strategic.mcallenProduceTerminal': 'Terminal de Productos de McAllen',
    'strategic.produceDistributionHub': 'Centro principal de distribución regional de productos',
    'strategic.majesticTradingPort': 'Puerto Comercial Internacional Majestic',
    'strategic.crossBorderLogistics': 'Instalación logística transfronteriza',
    'strategic.competitiveAdvantages': 'Ventajas Competitivas',
    'strategic.militaryHighwayFrontage': 'Frente a Military Highway con alta visibilidad y accesibilidad para camiones',
    'strategic.establishedCorridor': 'Corredor industrial establecido con demanda de inquilinos comprobada',
    'strategic.proximityBridges': 'Proximidad a tres puentes internacionales para acceso comercial diversificado',
    'strategic.infrastructureReady': 'Sitios listos para infraestructura eliminan retrasos y costos de desarrollo',

    // Property Specifications
    'properties.title': 'Especificaciones de Propiedades',
    'properties.premiumLots': '8 Lotes Industriales Premium Disponibles',
    'properties.professionalAnalysis': 'Análisis de Suscripción Profesional',
    'properties.locationDescription': 'Ubicado en el distrito industrial principal de McAllen con demanda logística comprobada.',
    'properties.correctedData': 'Datos corregidos',
    'properties.significantlyLarger': 'significativamente más grande de lo indicado en los materiales de marketing',
    'properties.aerialView': 'Vista Aérea - Desarrollo de Military Highway',
    'properties.siteBlueprint': 'Plano Detallado del Sitio',

    // Professional Underwriting
    'underwriting.professionalAnalysis': 'Análisis Profesional',
    'underwriting.location': '10th St & Military Hwy, Distrito Industrial de McAllen',
    'underwriting.landInvestment': 'Inversión en Terreno',
    'underwriting.siteCoverage': 'Cobertura del Sitio',
    'underwriting.withinNormalRange': 'Dentro del rango normal',
    'underwriting.aboveTypicalRange': 'Por encima del rango típico',
    'underwriting.belowEfficientRange': 'Por debajo del rango eficiente',
    'underwriting.landPerAcre': 'Terreno $/Acre',
    'underwriting.perAcreBasis': 'Base por acre',
    'underwriting.landPerSF': 'Terreno $/SF',
    'underwriting.perBuildableSF': 'Por SF edificable',
    'underwriting.planRentSF': 'Renta del Plan/SF',
    'underwriting.impliedFromPlan': 'Implícito del plan',
    'underwriting.planMarketAnalysis': 'Análisis Plan vs. Tarifa de Mercado',
    'underwriting.scenario': 'Escenario',
    'underwriting.rentSF': 'Renta/SF',
    'underwriting.annualNOI': 'NOI Anual',
    'underwriting.vsPlan': 'vs Plan',
    'underwriting.planProjection': 'Proyección del Plan',
    'underwriting.dryWarehouse12': 'Almacén Seco ($12/SF)',
    'underwriting.dryWarehouse125': 'Almacén Seco ($12.50/SF)',
    'underwriting.coldStorage18': 'Almacenamiento Frío ($18/SF)',
    'underwriting.upside': 'ventaja',
    'underwriting.strategicAdvantages': 'Ventajas Estratégicas',
    'underwriting.riskAssessment': 'Evaluación de Riesgos',
    'underwriting.coverageFlag': 'Bandera de Cobertura',
    'underwriting.below20Verify': 'Por debajo del 20% - verificar restricciones del sitio',
    'underwriting.above65Confirm': 'Por encima del 65% - confirmar cumplimiento de zonificación',
    'underwriting.investmentRecommendation': 'Recomendación de Inversión',
    'underwriting.positioningStrategy': 'Estrategia de Posicionamiento:',
    'underwriting.exportTearSheet': 'Exportar Hoja Informativa',
    'underwriting.runScenarios': 'Ejecutar Escenarios',

    // News Items
    'news.fedRates': 'El Fed podría reducir tasas a al menos 3%, dice Cabana de Bank of America',
    'news.fedRatesDesc': '36K vistas • Hace 4 días - Análisis experto sobre recortes de tasas del Federal Reserve y su impacto en inversiones inmobiliarias.',
    'news.interestRates': '¿Cómo impactará la baja de tasas de interés? | Hoy Día | Telemundo',
    'news.interestRatesDesc': 'Análisis sobre cómo los recortes de tasas afectarán las inversiones inmobiliarias y oportunidades de mercado.',
    'news.fedEnvironment': 'Análisis del Entorno de Tasas del Fed y su Impacto en Bienes Raíces Comerciales',
    'news.fedEnvironmentDesc': 'Perspectivas de expertos sobre cambios de tasas y estrategias de inversión inmobiliaria.',
    'news.powellAnalysis': 'Todo lo que el presidente del Fed, Powell, hizo \'DEMASIADO TARDE\' revelado',
    'news.powellAnalysisDesc': 'Hace 1 día - Análisis crítico de decisiones del Federal Reserve que afectan los mercados inmobiliarios comerciales.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};